<div class="full-width-box">
    <div id="custom-footer">
        <div id="footer-widget-box">

            <div id="footer-widget-box-3">
                <div class="textwidget">Copyright &copy; 2012 FormActivate • All Rights Reserved</div>

                <div class="clear"></div>
            </div>

            <div style="float:right">888-FORM-514 (888-367-6514)</div>

        </div>

    </div>
</div>

<!--[if lte IE 8]>
<div id="ie_clear"></div>
<![endif]-->
<script type="text/javascript"> Cufon.now(); </script>
<script type='text/javascript' src='<?php echo WEBSITE_URL . 'plugins/jquery.form.js' ?>'></script>
<script type='text/javascript' src='<?php echo WEBSITE_URL . 'plugins/scripts.js' ?>'></script>