<div class="full-width-box">
    <div id="custom-footer">
        <div id="footer-widget-box">

            <div id="footer-widget-box-1">
                <div class="footer-widget-row-1"><h2 class="widgettitle">how it works</h2>

                    <ul>
                        <li class="page_item page-item-6"><a href="<?php echo PUBLIC_SITE_URL?>demo-confirm/" title="Live Demo">Live Demo</a></li>

                        <li class="page_item page-item-8"><a href="<?php echo PUBLIC_SITE_URL?>pricing/" title="Pricing">Pricing</a></li>
                        <li class="page_item page-item-10"><a href="<?php echo PUBLIC_SITE_URL?>support/" title="Support">Support</a></li>
                        <li class="page_item page-item-12"><a href="<?php echo PUBLIC_SITE_URL?>blog/" title="Blog">Blog</a></li>
                        <li class="page_item page-item-14"><a href="<?php echo PUBLIC_SITE_URL?>contact/" title="Contact">Contact</a></li>
                        <li class="page_item page-item-25 current_page_item"><a href="<?php echo WEBSITE_URL?>" title="Home">Home</a></li>
                        <li class="page_item page-item-100"><a href="<?php echo PUBLIC_SITE_URL?>demo/" title="Demo">Demo</a></li>

                        <li class="page_item page-item-54"><a href="<?php echo WEBSITE_URL?>signin/" title="Signin">Signin</a></li>
                        <li class="page_item page-item-56"><a href="<?php echo WEBSITE_URL?>term-of-use/" title="Term of Use">Term of Use</a></li>
                        <li class="page_item page-item-169"><a href="<?php echo WEBSITE_URL?>privacy-policy/" title="Privacy Policy">Privacy Policy</a></li>
                        <li class="page_item page-item-176"><a href="<?php echo WEBSITE_URL?>about-us/" title="About Us">About Us</a></li>
                    </ul>
                </div><div class="footer-widget-row-1"><h2 class="widgettitle">demo</h2>

                    <ul>

                        <li class="page_item page-item-4"><a href="<?php echo PUBLIC_SITE_URL?>how-it-works/" title="How it Works-Live Demo">How it Works-Live Demo</a></li>
                        <li class="page_item page-item-8"><a href="<?php echo PUBLIC_SITE_URL?>pricing/" title="Pricing">Pricing</a></li>
                        <li class="page_item page-item-10"><a href="<?php echo PUBLIC_SITE_URL?>support/" title="Support">Support</a></li>
                        <li class="page_item page-item-12"><a href="<?php echo PUBLIC_SITE_URL?>blog/" title="Blog">Blog</a></li>
                        <li class="page_item page-item-14"><a href="<?php echo PUBLIC_SITE_URL?>contact/" title="Contact">Contact</a></li>
                        <li class="page_item page-item-25 current_page_item"><a href="<?php echo WEBSITE_URL?>" title="Home">Home</a></li>

                        <li class="page_item page-item-100"><a href="<?php echo PUBLIC_SITE_URL?>demo/" title="Demo">Demo</a></li>
                        <li class="page_item page-item-54"><a href="<?php echo WEBSITE_URL?>signin/" title="Signin">Signin</a></li>
                        <li class="page_item page-item-56"><a href="<?php echo WEBSITE_URL?>term-of-use/" title="Term of Use">Term of Use</a></li>
                        <li class="page_item page-item-169"><a href="<?php echo WEBSITE_URL?>privacy-policy/" title="Privacy Policy">Privacy Policy</a></li>
                        <li class="page_item page-item-176"><a href="<?php echo WEBSITE_URL?>about-us/" title="About Us">About Us</a></li>
                    </ul>
                </div><div class="footer-widget-row-1"><h2 class="widgettitle">pricing</h2>

                    <ul>
                        <li class="page_item page-item-4"><a href="<?php echo PUBLIC_SITE_URL?>how-it-works/" title="How it Works-Live Demo">How it Works-Live Demo</a></li>
                        <li class="page_item page-item-6"><a href="<?php echo PUBLIC_SITE_URL?>demo-confirm/" title="Live Demo">Live Demo</a></li>
                        <li class="page_item page-item-10"><a href="<?php echo PUBLIC_SITE_URL?>support/" title="Support">Support</a></li>
                        <li class="page_item page-item-12"><a href="<?php echo PUBLIC_SITE_URL?>blog/" title="Blog">Blog</a></li>
                        <li class="page_item page-item-14"><a href="<?php echo PUBLIC_SITE_URL?>contact/" title="Contact">Contact</a></li>

                        <li class="page_item page-item-25 current_page_item"><a href="<?php echo WEBSITE_URL?>" title="Home">Home</a></li>
                        <li class="page_item page-item-100"><a href="<?php echo PUBLIC_SITE_URL?>demo/" title="Demo">Demo</a></li>
                        <li class="page_item page-item-54"><a href="<?php echo WEBSITE_URL?>signin/" title="Signin">Signin</a></li>
                        <li class="page_item page-item-56"><a href="<?php echo WEBSITE_URL?>term-of-use/" title="Term of Use">Term of Use</a></li>
                        <li class="page_item page-item-169"><a href="<?php echo WEBSITE_URL?>privacy-policy/" title="Privacy Policy">Privacy Policy</a></li>
                        <li class="page_item page-item-176"><a href="<?php echo WEBSITE_URL?>about-us/" title="About Us">About Us</a></li>

                    </ul>
                </div><div class="footer-widget-row-1"><h2 class="widgettitle">support</h2>

                    <ul>
                        <li class="page_item page-item-4"><a href="<?php echo PUBLIC_SITE_URL?>how-it-works/" title="How it Works-Live Demo">How it Works-Live Demo</a></li>
                        <li class="page_item page-item-6"><a href="<?php echo PUBLIC_SITE_URL?>demo-confirm/" title="Live Demo">Live Demo</a></li>
                        <li class="page_item page-item-8"><a href="<?php echo PUBLIC_SITE_URL?>pricing/" title="Pricing">Pricing</a></li>
                        <li class="page_item page-item-12"><a href="<?php echo PUBLIC_SITE_URL?>blog/" title="Blog">Blog</a></li>

                        <li class="page_item page-item-14"><a href="<?php echo PUBLIC_SITE_URL?>contact/" title="Contact">Contact</a></li>
                        <li class="page_item page-item-25 current_page_item"><a href="<?php echo WEBSITE_URL?>" title="Home">Home</a></li>
                        <li class="page_item page-item-100"><a href="<?php echo PUBLIC_SITE_URL?>demo/" title="Demo">Demo</a></li>
                        <li class="page_item page-item-54"><a href="<?php echo WEBSITE_URL?>signin/" title="Signin">Signin</a></li>
                        <li class="page_item page-item-56"><a href="<?php echo WEBSITE_URL?>term-of-use/" title="Term of Use">Term of Use</a></li>
                        <li class="page_item page-item-169"><a href="<?php echo WEBSITE_URL?>privacy-policy/" title="Privacy Policy">Privacy Policy</a></li>

                        <li class="page_item page-item-176"><a href="<?php echo WEBSITE_URL?>about-us/" title="About Us">About Us</a></li>
                    </ul>
                </div><div class="footer-widget-row-1"><h2 class="widgettitle">contact</h2>

                    <ul>
                        <li class="page_item page-item-4"><a href="<?php echo PUBLIC_SITE_URL?>how-it-works/" title="How it Works-Live Demo">How it Works-Live Demo</a></li>
                        <li class="page_item page-item-6"><a href="<?php echo PUBLIC_SITE_URL?>demo-confirm/" title="Live Demo">Live Demo</a></li>
                        <li class="page_item page-item-8"><a href="<?php echo PUBLIC_SITE_URL?>pricing/" title="Pricing">Pricing</a></li>

                        <li class="page_item page-item-10"><a href="<?php echo PUBLIC_SITE_URL?>support/" title="Support">Support</a></li>
                        <li class="page_item page-item-12"><a href="<?php echo PUBLIC_SITE_URL?>blog/" title="Blog">Blog</a></li>
                        <li class="page_item page-item-25 current_page_item"><a href="<?php echo WEBSITE_URL?>" title="Home">Home</a></li>
                        <li class="page_item page-item-100"><a href="<?php echo PUBLIC_SITE_URL?>demo/" title="Demo">Demo</a></li>
                        <li class="page_item page-item-54"><a href="<?php echo WEBSITE_URL?>signin/" title="Signin">Signin</a></li>
                        <li class="page_item page-item-56"><a href="<?php echo WEBSITE_URL?>term-of-use/" title="Term of Use">Term of Use</a></li>

                        <li class="page_item page-item-169"><a href="<?php echo WEBSITE_URL?>privacy-policy/" title="Privacy Policy">Privacy Policy</a></li>
                        <li class="page_item page-item-176"><a href="<?php echo WEBSITE_URL?>about-us/" title="About Us">About Us</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>

            <div id="footer-widget-box-2">
                <div class="textwidget"><div id="seo-text">SEO text:  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</div></div>
                <div class="textwidget"><div id="address-text">FormActivate<br />3934 Murphy Canyon Road Suite B-200
                <br/>San Diego, CA 92123</div></div>


                <div class="clear"></div>
            </div>

            <div id="footer-widget-box-3">
                <div class="textwidget">Copyright © 2012 FormActivate • All Rights Reserved</div>

                <div class="clear"></div>
            </div>

            <div class="clear">888-FORM-514<br/>(888-367-6514)</div>

        </div>

    </div>
</div>

<!--[if lte IE 8]>
<div id="ie_clear"></div>
<![endif]-->
<script type="text/javascript"> Cufon.now(); </script>
<script type='text/javascript' src='<?php echo WEBSITE_URL . 'plugins/jquery.form.js' ?>'></script>
<script type='text/javascript' src='<?php echo WEBSITE_URL . 'plugins/scripts.js' ?>'></script>