<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: forms_left_panel.phttml	#
#			Description 	: this is menu to work in the front end site #
#			Created date	: 16/02/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
 $string=$_SERVER['REQUEST_URI'];
 $this->form_type;
$find='overview';
$find2='stdfield';
$find3='customfield';
$find4='opthrs';
$find5='businessrule';
$find6='emailnotification';
$find7='formredirect';
$find8='reporting';
$find9='preview';
$find10='formhtml';
$find11='wufooformfield';
$pos=strpos($string,$find);
$pos2=strpos($string,$find2);
$pos3=strpos($string,$find3);
$pos4=strpos($string,$find4);
$pos5=strpos($string,$find5);
$pos6=strpos($string,$find6);
$pos7=strpos($string,$find7);
$pos8=strpos($string,$find8);
$pos9=strpos($string,$find9);
$pos10=strpos($string,$find10);

$pos11=strpos($string,$find11);

$session = new Zend_Session_Namespace('Zend_Auth');

?>
<!--forms section left menu start here-->
<div class="maxheight col-1" style="width:220px;" >
        <div class="maxheight box">
            <div class="forms-padding">            		

                <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Create New Form " style="width: 56px; height: 22px;margin-bottom: 25px;clear: both;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Create New Form </cufontext></cufon></h2>
                <div class="account">
                    <ul>
                        <li class="title1"><strong>Setup</strong></li>
                        <li class="<?php if($pos===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/overview/form_id/<?php echo $this->form_id?>">Overview</a><?php if($session->overview_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php elseif($session->overview_visited): ?> <img title="This section is required" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Error.png'; ?>"/> <?php endif; ?></li>
                        <?php if($this->form_type == "wufoo") {?>
                        	<li class="<?php if($pos11===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/wufooformfield/form_id/<?php echo $this->form_id?>">Wufoo Form Fields</a><?php if($session->wufoo_form_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php elseif($session->wufoo_form_visited): ?> <img title="This section is required" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Error.png'; ?>"/> <?php endif; ?></li>
                        <?php }
                        	else
                        	{
                        ?>
	                        <li class="<?php if($pos2===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/stdfield/form_id/<?php echo $this->form_id?>">Standard Form Fields</a><?php if($session->standard_form_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php elseif($session->standard_form_visited): ?> <img title="This section is required" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Error.png'; ?>"/> <?php endif; ?></li>
	                        <li class="<?php if($pos3===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/customfield/form_id/<?php echo $this->form_id?>">Custom Form Fields</a><?php if($session->custom_form_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php else: ?> <img title="This section is optional" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Stop.png'; ?>"/> <?php endif; ?></li>
                        <?php }?>
                        <li class="<?php if($pos4===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/opthrs/form_id/<?php echo $this->form_id?>">Hours <br /> of Operation</a><?php if($session->hoo_form_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php else: ?> <img width="16" height="16" title="This section is optional" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Stop.png'; ?>"/> <?php endif; ?></li>
                        <li class="<?php if($pos5===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/businessrule/form_id/<?php echo $this->form_id?>">Business Rules</a><?php if($session->business_rule_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php else: ?> <img width="16" height="16" title="This section is optional" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Stop.png'; ?>"/> <?php endif; ?></li>
                        <li class="<?php if($pos6===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/emailnotification/form_id/<?php echo $this->form_id?>">Email <br /> Notification</a><?php if($session->emailnotification_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php elseif($session->emailnotification_visited): ?> <img title="This section is required" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Error.png'; ?>"/> <?php endif; ?></li>
                        <?php if($this->form_type != "wufoo")
                        {?>
                        	<li class="<?php if($pos7===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/formredirect/form_id/<?php echo $this->form_id?>">Form Redirect</a><?php if($session->redirect_done): ?><img title="This section is complete" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'OK.png'; ?>"/> <?php elseif($session->redirect_visited): ?> <img title="This section is required" width="16" height="16" class="form_stat" src="<?php echo WEBSITE_IMG_URL.'Error.png'; ?>"/> <?php endif; ?></li>
                        <?php 
                        }?>	
                        <li class="<?php if($pos8===false){ echo ""; } else {?> active<? }?>"><a href="<?php echo WEBSITE_URL?>forms/reporting/form_id/<?php echo $this->form_id?>">Reporting </a></li>
                    </ul>
                </div>
				<br>
                <div class="account">
                <?php if($this->form_type != "wufoo" && $this->form_type != "api") {?>
                    <ul>
						 <li class="billing"><strong>Form</strong></li>
                         <li <?php if($pos9===false){ echo ""; } else {?> class="active"<? }?>><a <?php if ($session->overview_done && $session->standard_form_done && $session->emailnotification_done && $session->redirect_done): ?> href="<?php echo WEBSITE_URL?>forms/preview/form_id/<?php echo $this->form_id?>" <?php else: ?> class="grayout"  <?php endif; ?> >Preview</a></li>
						 <li <?php if($pos10===false){ echo ""; } else {?> class="active"<? }?>><a <?php if ($session->overview_done && $session->standard_form_done && $session->emailnotification_done && $session->redirect_done): ?>  href="<?php echo WEBSITE_URL?>forms/formhtml/form_id/<?php echo $this->form_id?>" <?php else: ?> class="grayout"  <?php endif; ?>>Generate HTML</a></li>
					</ul>
				<?php }?>	
                </div>
            </div>
        </div>
</div>
<!--==============================content================================-->

