
<!--<body class="custom term-of-use">
<div id="header_area" class="full_width">

<div class="page">
	<div id="header">
		<p id="logo"><a href="http://form-active.wegrass.com">form@ctivate</a></p>
		<p id="tagline">Just another WordPress site</p>
	</div>
<div class="menu-menu-container"><ul id="menu-menu" class="menu"><li id="menu-item-102" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-102"><a href="http://form-active.wegrass.com/how-it-works/">How it Works</a></li>
<li id="menu-item-111" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-111"><a href="http://form-active.wegrass.com/demo/">Demo</a></li>
<li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="http://form-active.wegrass.com/pricing/">Pricing</a></li>

<li id="menu-item-112" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-112"><a href="http://form-active.wegrass.com/support/">Support</a></li>
<li id="menu-item-103" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-103"><a href="http://form-active.wegrass.com/blog/">Blog</a></li>
<li id="menu-item-45" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-45"><a href="http://form-active.wegrass.com/contact/">Contact</a></li>
</ul></div>

<div id="header-right-box">
	CALL 888-FORM-514	<a href="http://form-active.wegrass.com/signin" id="signin-bt" class="bt">Sign in</a></div>

</div>
</div>
<div id="content_area" class="full_width">-->


<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: header.thtml	#
#			Description 	: this is header to work in the front end site #
#			Created date	: 19/01/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
?>
<!--header start here <div class="extra-box" style="position:relative">-->
   	<header>
		<div class="row-1">
        	<h1><a class="logo" href="<?php echo WEBSITE_URL?>"></a></h1>        	
            <div class="extra-box">
            <span class="signin">
            <?php if($this->loggedin_customer_id>0){?>
			<a href="<?php echo WEBSITE_URL?>customers/logout" onmouseout="document.loginimage.src='<?php echo WEBSITE_URL?>images/logout.jpg'"  onmouseover="document.loginimage.src='<?php echo WEBSITE_URL?>images/logout-up.gif'"><img src="<?php echo WEBSITE_URL?>images/logout.jpg" name="logoutimage"></a>
			<?}else{ ?>
			<a href="<?php echo WEBSITE_URL?>customers/login" onmouseout="document.loginimage.src='<?php echo WEBSITE_URL?>images/login.jpg'"  onmouseover="document.loginimage.src='<?php echo WEBSITE_URL?>images/s-up.gif'"><img src="<?php echo WEBSITE_URL?>images/login.jpg" name="loginimage"></a>
			<? }?>	
            </span>
            	<ul class="menu" style="">
                	<li><a <?php if($this->actionName == 'index'){?> class="active"<? }?> href="<?php echo WEBSITE_URL?>">Home </a></li>
                   <!-- <li><a <?php if($this->actionName == 'services'){?> class="active"<? }?>href="<?php echo WEBSITE_URL?>index/services">Services </a></li>
                    <li><a <?php if($this->actionName == 'officesearch'){?> class="active"<? }?>href="<?php echo WEBSITE_URL?>index/officesearch">Office search </a></li>
                    <li><a <?php if($this->actionName == 'meetingrooms'){?> class="active"<? }?>href="<?php echo WEBSITE_URL?>index/meetingrooms">Meeting rooms </a></li>-->
                     <?php
						$obj=new Zend_Session_Namespace('Zend_Auth');
			
						if(isset($obj->member_id) && ($obj->user_type==0))
						{?>
						<li><a href="<?php echo WEBSITE_URL?>customers/myaccount">My Account </a></li>	
						<? }else if(isset($obj->member_id) && ($obj->user_type==1))
						{?>
						<li><a href="<?php echo WEBSITE_URL?>admin/">My Account </a></li>	
						<?
						}else{?>
						 <li><a <?php if($this->actionName == 'signup'){?> class="active"<? }?> href="<?php echo WEBSITE_URL?>customers/signup/">Sign Up</a></li>
						<? }			
					?>
                    <li><a <?php if($this->actionName == 'contacts'){?> class="active"<? }?>href="<?php echo WEBSITE_URL?>index/contacts">Contacts </a></li>
                </ul>
            </div>
        </div>
        <div class="row-2">
        	<div class="col-1">
            	<!-- faded slider begin -->
                <div id="faded">
                  <div class="rap">
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide1.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide2.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide3.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide4.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide5.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide6.jpg" width="619" height="425" alt="" /></a>
                  </div>   
                </div>
                <!-- faded slider end -->
            </div>
            <div class="col-2">
           	   	<div class="padding">
                	<h3>Specification</h3>
                    <ul class="list-top indent-bot2">
                    	<li><span>NewYork</span>City:</li>
                        <li><span>5TH Avenue</span>Street:</li>
                        <li><span>290 sq.ft</span>Office Size:</li>
                        <li><span>Brick, glass</span>Construction:</li>
                        <li><span>Modem ISDN</span>Internet Access:</li>
                        <li><span>Yes</span>Network (Cat.5):</li>
                        <li class="last-item"><span>Yes</span>Videoconferencing:</li>
                    </ul>
                    <div class="fright"><a class="button" href="#">Read more</a></div>
                    <span class="price"><strong>$ 4.589</strong><br>
                    p/month</span>
                </div>
            </div>
        </div>
    </header>
    
<!--==============================content================================-->
