<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: header.thtml	#
#			Description 	: this is header to work in the front end site #
#			Created date	: 19/01/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
?>
<!--header start here-->
    <header style="height:auto;">
			<div class="row-1">
        	<h1><a class="logo" href="<?php echo WEBSITE_URL?>"></a></h1>
            <div class="extra-box">
            	<div class="call">
                	Call as: <strong>+1 234 567 890</strong><br>
                    <time datetime="2010-08-18">(Monday - Friday 9am - 6pm GMT)</time>
                </div>
            </div>
            <div class="extra-box">
            	<ul class="menu1">
                <li><a href="<?php echo WEBSITE_URL?>">Home </a></li>
                    <li><a <?php if($this->actionName=="services"){?> class="active" <? }?> href="<?php echo WEBSITE_URL?>index/services">Services </a></li>
                    <li><a <?php if($this->actionName=="officesearch"){?> class="active" <? }?> href="<?php echo WEBSITE_URL?>index/officesearch">Office search </a></li>
                    <li><a <?php if($this->actionName=="meetingrooms"){?> class="active" <? }?> href="<?php echo WEBSITE_URL?>index/meetingrooms">Meeting rooms </a></li>
                    <?php
						$obj=new Zend_Session_Namespace('Zend_Auth');
			
						if(isset($obj->member_id) && ($obj->user_type==0))
						{?>
						<li><a href="<?php echo WEBSITE_URL?>customers/myaccount">My Account </a></li>	
						<? }else if(isset($obj->member_id) && ($obj->user_type==1))
						{?>
						<li><a href="<?php echo WEBSITE_URL?>admin/">My Account </a></li>	
						<?
						}			
					?>
                    <li><a <?php if($this->actionName=="contacts"){?> class="active" <? }?> href="<?php echo WEBSITE_URL?>index/contacts">Contacts </a></li>	
   	         	    <li><a <?php if($this->actionName=="virtualoffice"){?> class="active" <? }?> href="<?php echo WEBSITE_URL?>index/virtualoffice">Virtual office </a></li>                    
                </ul>
            </div>
        </div>
        <div class="row-2">
        	<div class="col-1">
            	<!-- faded slider begin -->
                <div id="faded">
                  <div class="rap">
                     <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide1.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide2.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide3.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide4.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide5.jpg" width="619" height="425" alt="" /></a>
                    <a href="#"><img src="<?php echo WEBSITE_URL?>images/slide6.jpg" width="619" height="425" alt="" /></a>
                  </div>   
                </div>
                <!-- faded slider end -->
            </div>
            <div class="col-2">
            	<div class="padding">
                	<h3>Specification</h3>
                    <ul class="list-top indent-bot2">
                    	<li><span>NewYork</span>City:</li>
                        <li><span>5TH Avenue</span>Street:</li>
                        <li><span>290 sq.ft</span>Office Size:</li>
                        <li><span>Brick, glass</span>Construction:</li>
                        <li><span>Modem ISDN</span>Internet Access:</li>
                        <li><span>Yes</span>Network (Cat.5):</li>
                        <li class="last-item"><span>Yes</span>Videoconferencing:</li>
                    </ul>
                    <div class="fright"><a class="button" href="#">Read more</a></div>
                    <span class="price"><strong>$ 4.589</strong><br>
                    p/month</span>
                </div>
            </div>
        </div>
    </header>
<!--==============================content================================-->
