<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: layout.thtml	#
#			Description 	: this is layout to work in the front end site #
#			Created date	: 19/01/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo WEBSITE_NAME;?></title>
    <meta charset="utf-8">
<link href="<?php echo WEBSITE_CSS_URL.'reset.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<link href="<?php echo WEBSITE_CSS_URL.'style.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<link href="<?php echo WEBSITE_CSS_URL.'layout.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'maxheight.js'?>"></script>
<script src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.faded.js'?>" type="text/javascript"></script>

	<!--[if lt IE 7]>
	<link href="<?php echo WEBSITE_CSS_URL.'ie/ie6.css'?>" media="screen" rel="stylesheet" type="text/css" >	    
    <script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'ie_png.js'?>"></script>
    <script type="text/javascript">
        ie_png.fix('.png, .pagination, .pagination li a');
    </script>
    <![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'html5.js'?>"></script>
    <![endif]-->
</head>
<?php
if($this->actionName == 'officesearch'){?>
<body id="page3" onLoad="new ElementMaxHeight();">
<? }    
?>
<?php
if($this->actionName == 'services'){?>
<body id="page2" onLoad="new ElementMaxHeight();">
<? }    
?>
<?php
if($this->actionName == 'meetingrooms'){?>
<body id="page4" onLoad="new ElementMaxHeight();">
<? }    
?>
<?php
if($this->actionName == 'contacts'){?>
<body id="page6" onLoad="new ElementMaxHeight();">
<? }    
?>
<?php
if($this->actionName == 'virtualoffice'){?>
<body id="page5" onLoad="new ElementMaxHeight();">
<? }    
?>



<div class="bg">
<div class="main">
<!--page start here-->		
		<?php
			$obj=new Zend_Session_Namespace('Zend_Auth');

			if(isset($obj->member_id) && ($obj->user_type==0))
			{
				//echo $this->render('header_loggedin.phtml');
			}else if(isset($obj->member_id) && ($obj->user_type==1))
			{
				//echo $this->render('header_admin.phtml');
			}else
			{
				//echo $this->render('header_index.phtml');
			}
			echo $this->render('header_services.phtml');
			
		?>
		<section id="content">
		<?php echo $this->layout()->content ?>
		</section>
		<?php echo $this->render('footer_index.phtml'); ?>	
   
<!--page end here-->
</div>
</div>
</body>
</html>