<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: layout.thtml	#
#			Description 	: this is layout to work in the front end site #
#			Created date	: 19/01/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
?>
<!DOCTYPE html>
<html lang="en">
<head>
<title><?php echo WEBSITE_NAME;?></title>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
</head>
<body>
Submitting your data. Please have patience... <?php echo $this->layout()->content ?>
</body>
</html>