<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: header.thtml	#
#			Description 	: this is header to work in the front end site #
#			Created date	: 19/01/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
?>
<!--header start here-->	
	<?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  	
            <div class="maxheight box">
                        <div class="">

                            <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Customer: " style="width: 56px; height: 22px;margin-bottom: 5px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Customer: </cufontext></cufon></h2>

                            <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="<?php if($this->firstname!=''){ echo htmlspecialchars(stripslashes(ucfirst($this->firstname))); echo "&nbsp;".htmlspecialchars(stripslashes(ucfirst($this->lastname))); }?>" style="width: 56px; height: 22px;margin-bottom: 25px;clear: both;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext><?php if($this->firstname!=''){ echo htmlspecialchars(stripslashes(ucfirst($this->firstname))); echo "&nbsp;".htmlspecialchars(stripslashes(ucfirst($this->lastname))); }?> </cufontext></cufon></h2>

                           		<div class="leftCol">
								<ul class="tabs">
									<li class="active" id="accountlitab"><a href="#" onclick="settabs('accountlitab','account','formlitab','forms')" style="cursor:pointer;">Account</a></li>
									<li id="formlitab"><a href="#"  style="cursor:pointer;" onclick="settabs('formlitab','forms','accountlitab','account')">Form</a></li>
								</ul>
							</div>
							<div id="account">							
								<div class="account">
									<ul>
										<li class="title1"><strong>Account</strong></li>
										<?php 
									if($_SESSION['Zend_Auth']['user_type']==0){?>
									<li <?php if($this->actionNameLeftPanel == 'left_customers'){?> class="active"<? }?>> <a href="<?php echo WEBSITE_URL?>customers/myaccount/id/<?php echo $this->id?>">Overview</a></li>
									<? }else{?>
									<!--  <li><a href="<?php echo WEBSITE_URL?>adminforms/index/cid/<?php echo $this->id?>">Form List</a></li> -->
									<li <?php if($this->actionNameLeftPanel == 'left_customers'){?> class="active"<? }?>> <a href="<?php echo WEBSITE_URL?>customers/edit/id/<?php echo $this->id?>">Overview</a></li>
									<? }?>
									<li <?php if($this->actionNameLeftPanel == 'editaccountdetails'){?> class="active"<? }?>>	
									<a href="<?php echo WEBSITE_URL?>customers/editaccountdetails/id/<?php echo $this->id?>">Edit Account Details </a></li>
									
									<li <?php if($this->actionNameLeftPanel == 'changepassword'){?> class="active" <? }?>><a href="<?php echo WEBSITE_URL?>customers/customerchangepassword/id/<?php echo $this->id?>">Change Password<a/></li>
									<li <?php if($this->actionNameLeftPanel == 'editplandetails'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/editplandetails/id/<?php echo $this->id?>">Edit Plan Details</a></li>
									</ul>
								</div>
								
								<br>
                            	<div class="account">
                                <ul>
									<li class="billing"><strong>Billing</strong></li>
									<li <?php if($this->actionNameLeftPanel == 'billinghistory'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/billinghistory/id/<?php echo $this->id?>">Billing History</a></li>
									<li <?php if($this->actionNameLeftPanel == 'editpaymentdetails'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/editpaymentdetails/id/<?php echo $this->id?>">Edit Payment Details</a></li>
									<li <?php if($this->actionNameLeftPanel == 'cancelsubscription'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/cancelsubscription/id/<?php echo $this->id?>">Cancel Subscription</a></li>
								</ul>
                            </div>   
                            </div>                         	
							
							<div id="forms" style="display:none;">
								<div class="account">
									<ul>
										<li class="title1"><strong>Setup</strong></li>
										<!--<li>Overview</li>
										<li>Standard Form Fields</li>
										<li>Custom Form Fields</li>
										<li>Hours of Operations</li>
										<li>Business Logic</li>
										<li>Email Notification</li>
										<li>Form Redirect</li>
										<li>Reporting</li>-->
										<li><a href="<?php echo WEBSITE_URL?>adminforms/index/cid/<?php echo $this->id?>">Form List</a></li>
										 <li><a href="<?php echo WEBSITE_URL?>adminforms/overview/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Overview</a></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/stdfield/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Standard Form Fields</a></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/customfield/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Custom Form Fields</a></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/opthrs/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Hours of Operations</a></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/businessrule/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Business Logic</a></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/emailnotification/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Email Notification</a></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/formredirect/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Form Redirect</a></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/reporting/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Reporting</a></li>
									</ul>
								</div>
								<br>
                            	<div class="account">
                                <ul>
						<li class="billing"><strong>Form</strong></li>
						<li><a href="<?php echo WEBSITE_URL?>adminforms/preview/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Preview</a></li>
						    <li><a href="<?php echo WEBSITE_URL?>adminforms/formhtml/form_id/<?php echo $this->form_id?>/cid/<?php echo $this->id?>">Generate HTML</a></li>
					
								</ul>
                            </div>
							</div>
							
                        </div>
                    </div>
           <? }else{?> 

<h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="My Account " style="width: 56px; height: 22px;margin-bottom: 25px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>My Account </cufontext></cufon></h2>

     <div class="account">
                                <ul>
									<li class="title1"><strong>Account</strong></li>
									<?php 
									if($_SESSION['Zend_Auth']['user_type']==0){?>
									<li <?php if($this->actionNameLeftPanel == 'left_customers'){?> class="active"<? }?>> <a href="<?php echo WEBSITE_URL?>customers/myaccount/id/<?php echo $this->id?>">Overview</a></li>
									<? }else{?> 
									<li <?php if($this->actionNameLeftPanel == 'left_customers'){?> class="active"<? }?>> <a href="<?php echo WEBSITE_URL?>customers/edit/id/<?php echo $this->id?>">Overview</a></li>
									<? }?>
									<li <?php if($this->actionNameLeftPanel == 'editaccountdetails'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/editaccountdetails/id/<?php echo $this->id?>">Edit Account Details</a></li>									
									<li <?php if($this->actionNameLeftPanel == 'changepassword'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/changepassword/id/<?php echo $this->id?>">Change Password</a></li>
									<li <?php if($this->actionNameLeftPanel == 'editplandetails'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/editplandetails/id/<?php echo $this->id?>">Edit Plan Details</a></li>
								</ul>
                            </div>
							<br>
                            <div class="account">
                                <ul>
									<li class="billing"><strong>Billing</strong></li>
									<li <?php if($this->actionNameLeftPanel == 'billinghistory'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/billinghistory/id/<?php echo $this->id?>">Billing History</a></li>
									<li <?php if($this->actionNameLeftPanel == 'editpaymentdetails'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/editpaymentdetails/id/<?php echo $this->id?>">Edit Payment Details</a></li>
									<li <?php if($this->actionNameLeftPanel == 'cancelsubscription'){?> class="active"<? }?>><a href="<?php echo WEBSITE_URL?>customers/cancelsubscription/id/<?php echo $this->id?>">Cancel Subscription</a></li>
								</ul>
      </div> 
      
        <?php 
							if($_SESSION['Zend_Auth']['user_type']!=0){?><br>
                            <div class="account">
                                <ul>
									<li class="billing"><strong>Miscellaneous</strong></li>
                            		<li><a href="<?php echo WEBSITE_URL?>admin/pages">Corporate Page</a></li>											    <li><a href="<?php echo WEBSITE_URL?>admin/businessrule">Business Rule</a></li>											<li><a href="<?php echo WEBSITE_URL?>admin/inquiry">Inquiry</a></li>	
							</div>
							<? }?>
        <? }?>
<!--==============================content================================-->

<script type="text/javascript">
function settabs(tabidfirst,dividfirst,tabidsecond,dividsecond){	
jQuery('#'+tabidfirst).show();	
jQuery('#'+tabidfirst).addClass('active');	
jQuery('#'+tabidsecond).removeClass('active');	
jQuery('#'+dividfirst).show();	
jQuery('#'+dividsecond).hide();	
}
</script>