<div style='border: 1px solid #DDDDDD;min-height: 250px;overflow: hidden;padding: 15px;'>
    <img src='<?php echo WEBSITE_IMG_URL."branding.png"; ?>' /> <hr />
    <div style='color:black;'>Hello  <?php echo $this->firstname ?> ,<br><br>
        For resetting your password please click given URL.<br><br>
        <a href="<?php echo WEBSITE_URL . "customers/resetpassword/reset_link/" . $this->reset_link; ?>">Click here</a>
        <br><br> Thanks <br><span style='color:black;'> <?php echo WEBSITE_NAME; ?></span></div>
</div>