<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: customfield.phtml	#
#			Description 	: this is 3rd step to create form builder
#			Created date	: 16/02/2011	#	
#			Created By		: Saurabh Agarwal						#
######################################################
?> 
<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>
<script type="text/javascript">


    jQuery(document).ready(function($){

                $('.buttonsNextPreviewSignin[title], .ptip[title]').qtip({
                   position: {
                       my: 'right center',
                       at: 'left center'
                    },
                    style: {
                       classes: ''
                    }
                });

                $('.chelp[title]').qtip({
                   position: {
                       my: 'left center',
                       at: 'right center'
                    },
                    style: {
                       classes: ''
                    }
                });
});

</script>
<div class="row-1 wrapper">
<?php  
echo $this->render('forms_left_panel.phtml'); 
$i=0;
foreach($this->selected_fields as $selected_fields)
{
	$labels[$i]=$selected_fields['label'];
	$fields_required[$i]=$selected_fields['field_required'];
	$fields_validate[$i]=$selected_fields['field_validate'];
	$field_announce[$i]=$selected_fields['field_announce'];	
	$selected_field_data_type[$i]=$selected_fields['data_type'];
	$i++;
}
?>
   

 		 
            <article class="maxheight col-2" style="width: 630px;">
            <form id="formID1" name="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>forms/customfield/form_id/<?=$this->form_id?>" />
                <div class="box" style="height:455px;">
                    <div class="forms-padding">   
                     <span style="float:right;">
                             <?php $session = new Zend_Session_Namespace('Zend_Auth'); if ($session->overview_done && $session->standard_form_done && $session->emailnotification_done && $session->redirect_done): ?>
                             <a style="border: solid 1px #CECECE;color: #949494;padding: 5px;" href="<?php echo WEBSITE_URL?>forms/preview/form_id/<?php echo $this->form_id?>" title="<?php echo STDFIELD_PREVIEW; ?>" type="button" class="buttonsNextPreviewSignin">Preview Form</a>
                             <?php else: ?>

                                <span class="ptip" title="<?php echo STDFIELD_PREVIEW; ?>" style="border: solid 1px #CECECE;color: #949494;padding: 5px;">
                                    Preview Form
                                </span>
                             <?php endif; ?>
                        </span>

                        <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Custom Form Fields " style="width: 56px; height: 22px;margin-bottom: 25px;clear: both;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Custom Form Fields </cufontext></cufon></h2>
                        <div id="formUserDetailsStd">
                            <b title="<?php echo CUSTOME_FORM_HELP; ?>" class="chelp">What is custom form field? <img alt="no image" src='<?php echo WEBSITE_URL . 'images/info_icon.png' ?>' width="18" />  </b><br /><br />
                        	<table cellpadding="0" cellspacing="0" width="100%">
                        	<tr>
                        	    <td><b>Field Type</b></td>
		                  		<td><b>Label</b></td>
		                  		<?php if($this->form_type == "api")
		                  		{
		                  		?>
		                  		<td><b>Field Name</b></td>
		                  		<?php } else {?>
		                  		<td><b>Data Type</b></td>
		                  		<?php }?>
		                     	<td><b>Required</b></td>
		                  		<td><b>Validation Type</b></td>
		                  		<td><b>Announce</b></td>
		                  		
		                  	</tr>
                        <?php
                        for($i=0;$i<5;$i++)
                        {
                        	//echo $fields['label'].'<br/>';	
                        	
                        	if($i%2==0)
                        	{
                        		$style="style='background-color:#EFF0F0'";
                        	}
                        	else {
                        		$style="";
                        	}
                        ?>
                  	      	<tr>
                  	      		<td <?=$style?>>Custom Field <?=$i+1?></td>
		                  		<td <?=$style?>><input type="text" name="label[<?=$i?>]" value="<?php if(isset($labels[$i])) echo $labels[$i]; else echo '';?>" /></td>
		                  		
		                  		
		                  		<td <?=$style?>>
		                  		
		                  		<?php if($this->form_type == "api")
		                  		{
		                  			echo "custom".($i+1);
		                  		?>
		                  			
		                  		<?php } else {?>
			                  		<?php
			                  		$val3='';
			                  		if(isset($selected_field_data_type[$i]))
			                  		{
			                  			$val3=$selected_field_data_type[$i];
			                  		}
			                  		?>
			                  		<select name="field_data_type[<?=$i?>]" >
								                  		 <option value="text" <?php if($val3=='text') { echo "selected='selected'"; }?> >Text Box</option>
	                                                        <option value="textarea" <?php if($val3=='textarea') { echo "selected='selected'"; }?> >Paragraph</option>
								                  	</select>
								           <?php }?>       	
							                  	
		                  		</td>
		                  		
		                  		
		                  		<td <?=$style?>>
		                  		<?php
		                  		$val1='';
		                  		if(isset($fields_required[$i]))
		                  		{
		                  			$val1=$fields_required[$i];
		                  		}
		                  		?>
		                  		<select name="field_required[<?=$i?>]" style="width:73px;">
							                  		<option value="no" <?php if($val1=='no') echo " selected='selected'";?>>No</option>
							                  		<option value="yes" <?php if($val1=='yes') echo " selected='selected'";?>>Yes</option>
							                  	</select>
							                  	
		                  		</td>
		                  		<td <?=$style?>>
		                  		<?php
		                  		$val2='';
		                  		if(isset($fields_validate[$i]))
		                  		{
		                  			$val2=$fields_validate[$i];
		                  		}
		                  		?>
		                  		
		                  		<select name="field_validate[<?=$i?>]">
							                  		<option value="none" <?php if($val2=='none') echo " selected='selected'";?>>None</option>
							                  		<option value="email" <?php if($val2=='email') echo " selected='selected'";?>>Email</option>
							                  		<option value="zip" <?php if($val2=='zip') echo " selected='selected'";?>>Zip</option>
							                  		<option value="phone" <?php if($val2=='phone') echo " selected='selected'";?>>Phone</option>
		                  						</select>
		                  		</td>		                  		
		                  		
		                  		<td <?=$style?>>
		                  		<?php
		                  		$val3='';
		                  		if(isset($field_announce[$i]))
		                  		{
		                  			$val3=$field_announce[$i];
		                  		}
		                  		?>
		                  		<select name="field_announce[<?=$i?>]" style="width:73px;">
							                  		<option value="no" <?php if($val3=='no') echo " selected='selected'";?>>No</option>
							                  		<option value="yes" <?php if($val3=='yes') echo " selected='selected'";?>>Yes</option>
							                  	</select>
							                  	
		                  		</td>
		                  		
		                  		
		                  		
		                  		
		                  		
		                  		
		                  		
		                  	</tr>
                          	
                        <?php
						
                         }
                        ?>
                        
                        </table>
                        </div>
                         <div class="buttonsNextPrev">                                
                           <input class="buttonsNext" style="width:90px;" type="button" value="Previous"  onclick="go_prev('Previous');"/>
                           <input class="buttonsNext" style="width:90px;" type="button" value="Next"  onclick="go_prev('Next')"/>
                            <input type="hidden" name="preview_hidden_value" id="preview_hidden_value" value="<?php echo $this->preview_hidden_value;?>">  
                             <input type="hidden" name="formid" id="formid" value="<?php echo $this->form_id;?>">   
                              <input type="hidden" name="form_action" id="form_action" value="">    	 	                       	
                         </div>      	
                     </div>
                </div>
                </form>
            </article>
</div> 
<div id="previewhiddendiv"></div>
<script type="text/javascript">
 function validate_form(){
              // binds form submission and fields to the validation engine             
				jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
 }

 
 function go_prev(type)
 {
	jQuery('#form_action').val(type);
	//exit;
 	validate_form();
 	//document.form.submit();
 	document.formID1.submit();
 	//var myString = '<?=WEBSITE_URL?>'+'forms/overview/form_id/'+'<?=$this->form_id;?>';	window.location=myString;
 }
 
</script>
<script type="text/javascript">
function validate_form(){
              // binds form submission and fields to the validation engine
           	  jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
 }
 
function getpreview(formid){ 		
		var id=formid;
		jQuery.post("<?php echo WEBSITE_URL?>forms/popupcustompreview",{form_id:id},function(response){		
				if(response!=''){
					jQuery("#previewhiddendiv").show();
					jQuery('#previewhiddendiv').html(response);	
				}else{
				jQuery('#previewhiddendiv').html('');				
				}				
		});	
}
function hideme(hidediv){              
           	  jQuery("#"+hidediv).hide();
 }
 
 function savepreviewform(){  	         
       jQuery('#preview_hidden_value').val('1');				       
       document.formID1.submit();
 } 
 

$(document).ready(function() {
	 var preview_hidden_value=jQuery('#preview_hidden_value').val();	
	if(preview_hidden_value==2){
  var id=jQuery('#formid').val();
		jQuery.post("<?php echo WEBSITE_URL?>forms/popupcustompreview",{form_id:id},function(response){		
				if(response!=''){
					jQuery("#previewhiddendiv").show();
					jQuery('#previewhiddendiv').html(response);	
				}else{
				jQuery('#previewhiddendiv').html('');				
				}									
		});	
		jQuery('#preview_hidden_value').val('');
	}else{
	jQuery('#preview_hidden_value').val('');	
	}
});

</script>