
<div id="title-box"><h1><cufon style="width: 124px; height: 40px;" alt="Contact" class="cufon cufon-canvas"><canvas style="width: 154px; height: 39px; top: 0px; left: -1px;" height="39" width="154"></canvas><cufontext>Contact</cufontext></cufon></h1></div>
<div id="content_box" class="no_sidebars">
    <div id="content">

        <div class="post_box top" id="post-14">
            <div class="format_text">
                <div class="full-box-center-border">
                    <div class="half-box">
                        Can't find what you're looking for on the <a href="<?php echo PUBLIC_SITE_URL ?>support/">Support page</a>? Want to leave us some feedback? We'd love to hear from you! Just use the form to the right.<p></p>
                        <h2>By Phone:</h2>
                        <p><strong>858-755-5433</strong><br>
                            Mon-Fri 8:00 am - 4:00 pm PST
                        </p></div>
                    <div class="half-box last">
                        <div id="contact-form">
                            <h2 class="contact-form-title">By Email:</h2>
                            <div class="wpcf7" id="wpcf7-f1-p14-o1"><form action="/contact/#wpcf7-f1-p14-o1" method="post" class="wpcf7-form">
                                    <div style="display: none;">
                                        <input name="_wpcf7" value="1" type="hidden">
                                        <input name="_wpcf7_version" value="2.4.6" type="hidden">
                                        <input name="_wpcf7_unit_tag" value="wpcf7-f1-p14-o1" type="hidden">
                                    </div>
                                    <p><label for="contact-name">Name</label><span class="wpcf7-form-control-wrap your-name"><input name="your-name" value="" id="contact-name" class="wpcf7-text wpcf7-validates-as-required" size="40" type="text"></span> </p>
                                    <p><label for="contact-company">Company</label><span class="wpcf7-form-control-wrap your-company"><input name="your-company" value="" id="contact-company" class="wpcf7-text" size="40" type="text"></span> </p>
                                    <p><label for="contact-email">Email</label><span class="wpcf7-form-control-wrap your-email"><input name="your-email" value="" id="contact-email" class="wpcf7-text wpcf7-validates-as-email wpcf7-validates-as-required" size="40" type="text"></span> </p>
                                    <p><label for="contact-about">Inquiring about...</label><span class="wpcf7-form-control-wrap your-about"><textarea name="your-about" id="contact-about" cols="40" rows="10"></textarea></span></p>
                                    <p></p><div class="wpcf7-response-output wpcf7-display-none"></div><p></p>
                                    <p><input value="Contact Us" class="wpcf7-submit" type="submit"><img class="ajax-loader" style="visibility: hidden;" alt="Sending ..." src="http://www.formactivate.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif"></p>
                                </form></div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div id="bottom-box">
    <div class="clear"></div>
</div>
<div class="clear"></div>