<div id="title-box"><h1><cufon style="width: 81px; height: 40px;" alt="Contact " class="cufon cufon-canvas"><canvas style="width: 113px; height: 39px; top: 0px; left: -1px;" height="39" width="113"></canvas><cufontext>Contact </cufontext></cufon></h1></div>
<div class="row-1 wrapper">

        
	<article class="maxheight col-1">
            <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Contact Form " style="width: 56px; height: 22px;margin-left: 30px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Contact Form </cufontext></cufon></h2>
	<div class="maxheight box" style="margin-top: -13px;">
		<div class="padding">
			<form action="" enctype="multipart/form-data" id="form-main" method="post">
				<fieldset>
					<label>
                                            <input name="name" onblur="if(this.value=='') this.value='Your Name:'" onfocus="if(this.value =='Your Name:' ) this.value=''" value="Your Name:">
                                        </label>
                                    <label>
                                        <input name="name" onblur="if(this.value=='') this.value='E-mail:'" onfocus="if(this.value =='E-mail:' ) this.value=''" value="E-mail:">
                                    </label>
                                    <textarea onblur="if(this.value=='') this.value='Message:'" onfocus="if(this.value =='Message:' ) this.value=''">Message:</textarea>
			
                                    <br /><br /><input type="submit" onclick="document.getElementById('form-main').submit()" class="big-orange-bt centered center" value="Contact Us" name="submit">

				</fieldset>

			</form>
		</div>
	</div>
	</article>
    <article class="maxheight col-2" style="width:548px">
            <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Our Departments " style="width: 56px; height: 22px;margin-left: 30px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Our Departments </cufontext></cufon></h2>
	<div class="maxheight box">
		<div class="padding">			
                    <p class="font_size_15">
				Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fu sce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristiq ue orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. <br /><br /></p>
			<div class="wrapper">
				<div class="col-1" style="font-size: 13px;">
					<dl class="p2">
						<dt>
							Customer Service:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:customers@cdemolink.org">customers@cdemolink.org</a></dd>
					</dl>
					<dl class="p2">
						<dt>
							Risk management dept:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:risk@demolink.org">risk@demolink.org</a></dd>
					</dl>
					<dl class="p2">
						<dt>
							Network planning service:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:planning@demolink.org">planning@demolink.org</a></dd>
					</dl>
					<dl class="p2">
						<dt>
							Target marketing office:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:marketing@demolink.org">marketing@demolink.org</a></dd>
					</dl>
                                    <dl class="p2">
						<dt>
							Web site questions:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:webmaster@cdemolink.org">webmaster@cdemolink.org</a></dd>
					</dl>
					<dl class="p2">
						<dt>
							Job opportunities:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:jobs@demolink.org">jobs@demolink.org</a></dd>
					</dl>
				</div>
				<div class="col-2" style="font-size: 13px;">
					<dl class="p2 mar_left_30">
						<dt>
							Investor relations:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:investors@cdemolink.org">investors@cdemolink.org</a></dd>
					</dl>
					<dl class="p2 mar_left_30">
						<dt>
							Training center:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:training@demolink.org">training@demolink.org</a></dd>
					</dl>
					<dl class="p2 mar_left_30">
						<dt>
							Support department:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:support@demolink.org">support@demolink.org</a></dd>
					</dl>
					<dl class="p2 mar_left_30">
						<dt>
							Sales department:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:sales@demolink.org">sales@demolink.org</a></dd>
					</dl>
				
					
					<dl class="p2 mar_left_30">
						<dt>
							Innovations information:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:innovations@demolink.org">innovations@demolink.org</a></dd>
					</dl>
					<dl class="p2 mar_left_30">
						<dt>
							Press relations:</dt>
						<dd>
							<span>Telephone:</span> +1 959 603 6035</dd>
						<dd>
							<span>FAX:</span> +1 101 889 9898</dd>
						<dd>
							<a href="mailto:press@demolink.org">press@demolink.org</a></dd>
					</dl>
				</div>
			</div>
		</div>
	</div>
	</article>

    </div>
<div class="row-2 wrapper">
	&nbsp;</div>

<!--==============================content end here================================-->    