<!--==============================content start here================================-->

<div id="title-box"><h1>
	Home	</h1></div>
<div id="content_box">
    <h2 id="home-title">Never miss a website lead again!</h2>
    <div id="home-tagline">Respond to quality leads instantly - Ignore lesser leads</div>
    <div id="home-featured">
        <div id="home-contact"><div class="wpcf7" id="wpcf7-f6-t1-o1"><form action="/#wpcf7-f6-t1-o1" method="post" class="wpcf7-form">
                    <div style="display: none;">
                        <input type="hidden" name="_wpcf7" value="6" />

                        <input type="hidden" name="_wpcf7_version" value="2.4.6" />
                        <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f6-t1-o1" />
                    </div>
                    <p><label for="home-contact-name">Contact Us</label><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" id="home-contact-name" class="wpcf7-text wpcf7-validates-as-required wpcf7-use-title-as-watermark" size="40" title="Bob Johnson" /></span> </p>
                    <p><span class="wpcf7-form-control-wrap your-email"><input type="text" name="your-email" value="" id="contact-email" class="wpcf7-text wpcf7-validates-as-email wpcf7-validates-as-required wpcf7-use-title-as-watermark" size="40" title="bob@Pacificbusinessservices.com" /></span> </p>
                    <p><label id="label-home-number" for="home-contact-number">Callback number:</label><span class="wpcf7-form-control-wrap span-your-number"><input type="text" name="span-your-number" value="" id="home-contact-number" class="wpcf7-text wpcf7-use-title-as-watermark" size="40" title="619-999-2026" /></span> <br class="clear" /></p>
                    <p><span class="wpcf7-form-control-wrap your-about"><textarea name="your-about" id="home-contact-about" class="wpcf7-use-title-as-watermark" cols="40" rows="10" title="Hi! Can you you install 2 units by the end of next week?"></textarea></span></p>
                    <p><div class="wpcf7-response-output wpcf7-display-none"></div></p>
                </form></div></div>
        <div id="home-iphone"></div>

        <div id="home-balloon">
            Speak with prospects instantly using text-to-speech technology!
        </div>
        <div id="home-try">
            <ul>
                <li><a href="<?php echo PUBLIC_SITE_URL ?>demo/">Try the demo</a></li>
                <li><a href="<?php echo PUBLIC_SITE_URL ?>index/pricing/">Compare plans</a></li>
            </ul>

            <a id="free-trail-bt" href="#">Start Free Trial</a>
        </div>
    </div>
    <div id="home-content">

        <div class="left">
            <h2>First response usually gets the business</h2>
            <p>
                <strong>90% of users choose a service profession based on who calls them back first.</strong>

                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <h2>Call back, save for later or ignore</h2>
            <p>
                Any leads from your website will be instantly routed to your phone as a voicemail. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.t
            </p>
        </div>

        <div class="center">
            <a id="screen-play" href="#"><img src="<?php echo WEBSITE_URL . 'images/screen-play.png' ?>" /></a>

            <p><a href="#">Learn how easily you can implement FormActivate on your site and start turning your leads into dollars</a></p>
        </div>

        <div class="right">
            <ul>
                <li>Monthly plans start at only $9.99 per month</li>
                <li>Free 7-day trial</li>
                <li>Easy install</li>

                <li>Phone support</li>
                <li>Reportning & Stats</li>
            </ul>

        </div>
    </div>	</div>

<div id="bottom-box">
    <div class="clear"></div>
</div>

<div class="clear"></div>


<!--==============================content end here================================-->    