
<div id="title-box"><h1><cufon style="width: 127px; height: 40px;" alt="Support" class="cufon cufon-canvas"><canvas style="width: 157px; height: 39px; top: 0px; left: -1px;" height="39" width="157"></canvas><cufontext>Support</cufontext></cufon></h1></div>

<div id="content_box" class="no_sidebars">
    <div id="content">
        <div class="post_box top" id="post-10">
            <div class="format_text">
                <p>This is how you contact support: <br />
                    High Clarity, LLC <br />
                    10821 Calle Mar De Mariposa <br />
                    Sandiego, CA 92130 858-755-5433 <br />
                </p>
            </div>
        </div>
    </div>

</div>

<div id="bottom-box">
    <div class="clear"></div>
</div>
<div class="clear"></div>

