<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: signup.phtml	#
#			Description 	: this is First signup Page  to work in the front end site #
#			Created date	: 19/01/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
?> 
<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>

<script type="text/javascript">

    jQuery(document).ready(function($){

                $('input[title]').qtip({
                   position: {
                       my: 'left center',
                       at: 'right center'
                    },
                    style: {
                       classes: ''
                    }
                });
});

</script>
<form id="formID1" name="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>customers/customerchangepassword/id/<?php echo $this->id?>">
 		<div class="row-1 wrapper">   
 			<? /*if($this->user_type==1 && $this->id==1){?>
             <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-1" style="width:307px;" <? }else{?> class="maxheight col-1" style="width:220px;"<? }?> >
                    <div class="maxheight box">
                        <div class="padding">       
						<?php echo $this->render('admin_logged_in_left_panel.phtml'); ?>                 
                       
                        </div>
                    </div>
            </article>
            <? }else {*/?>            
            <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-1" style="width:307px;" <? }else{?> class="maxheight col-1" style="width:220px;"<? }?> >
                    <div class="maxheight box">
                        <div class="padding">
                       <?php echo $this->render('logged_in_left_panel.phtml'); ?>               							
                        </div>
                    </div>
            </article> 
            <? // }?>  
                       
               <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-2" style="width:548px;" <? }else{?> class="maxheight col-4" style="width:706px;"<? }?> >
                <div class="maxheight box">
                    <div class="padding"> 

                     <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Change Password " style="width: 56px; height: 22px;margin-bottom: 25px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Change Password </cufontext></cufon></h2>
                     <?php if($this->Errormsg){ ?><p  style="color:black;font-weight:600;" id="errorcon"> <? echo $this->Errormsg; ?> </p><? }?>                     
                        <div id="formcompanyDetails">
                            <fieldset>
                               <?php if($this->id !=1){?>
                               <input type="hidden"  name="password" id="password"  value="1234567qwertyu"><?}else {?>   
                            	<label><span>Old Password<strong>*</strong></span><input type="password"  name="password" id="password"  value="" class="validate[required,custom[pass]]" onblur="hide_by_id('span_password1')" />                            	                       					<div class="formError" style="display:none;top: 252px; left: 636px; margin-top: 0px; opacity: 0.87;" id="span_password1"><div class="formErrorContent" id="span_password">* This field is required<br>* Invalid name <br></div></div>
                            	</label>  
                            <? }?>
                            	
                            	
                            	<label><span>Password<strong>*</strong></span><input title="<?php echo SIGNUP_PASS1; ?>" type="password"  name="newpassword" id="newpassword"  value="<?php //echo (isset($this->data->pass))? htmlspecialchars(stripslashes($this->data->pass)) : '';?>"  class="validate[required,custom[pass]]"  onblur="hide_by_id('span_password2')"/>
                            	<div class="formError" id="span_password2" style="display:none; <?php if($this->i_m_admin==1){?>
  top: 188px; left: 723px; <?}else{ ?>top: 300px; left: 636px;<? }?> margin-top: 0px; opacity: 0.87;"><div class="formErrorContent" id="span_newpassword">* This field is required<br>* Invalid name <br></div></div>
                            	</label>
                                <label><span>Re-type Password<strong>*</strong></span><input title="<?php echo SIGNUP_PASS2; ?>" type="password"   name="conpassword" id="conpassword"  value="<?php //echo (isset($this->data->pass))? htmlspecialchars(stripslashes($this->data->pass)) : '';?>" onblur="hide_by_id('span_password3')"/>
                                <div class="formError" id="span_password3" style="display:none; <?php if($this->i_m_admin==1){?>
  top: 241px; left: 723px; <?}else{ ?>top: 350px; left: 636px;<? }?> margin-top: 0px; opacity: 0.87;"><div class="formErrorContent" id="span_conpassword">* This field is required<br>* Invalid name <br></div></div>
                                </label>
                                <div class="buttonsNextPrev">                                
								 <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?> 
								 <input class="buttonsNext" style="width:90px;" type="button" value="Cancel"  onclick="window.location.href='<?php echo WEBSITE_URL?>customers/edit/id/<?php echo $this->id?>'"/>  <? }else{?> <input class="buttonsNext" style="width:90px;" type="button" value="Cancel"  onclick="window.location.href='<?php echo WEBSITE_URL?>customers/myaccount/id/<?php echo $this->id?>'"/> <? }?>
                                <input class="buttonsNext" style="width:90px;" type="submit" value="Update"  onclick="return validate()"/> 
                               <input type="hidden"  name="id" id="id"   value="<?php echo (isset($this->id))? htmlspecialchars(stripslashes($this->id)) : '';?>"/>                                
                       			<input type="hidden"  name="oldemail" id="oldemail"   value="<?php echo (isset($this->id))? htmlspecialchars(stripslashes($this->email)) : '';?>"/>                                
                               	<!--	<a class="buttonsNext" onclick="validate_signup()">Next</a>-->
                                </div>                               
                            </fieldset> 
                            </div>                        
                    </div>
                </div>
            </article>
        </div>      
 	</form>        
<script type="text/javascript">
 function validate_signup(){
              // binds form submission and fields to the validation engine
             	//jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});            
 }
 
 function validate_confirm_pass(){ 
	var pass1=jQuery('#newpassword').val();
	var pass2=jQuery('#conpassword').val();
	if(pass1!=pass2){		
		jQuery('#passwordnotmatched').show();
		//jQuery('#conpassword').val('');
		jQuery('#conpassword').focus();
		//setTimeout("jQuery('#passwordnotmatched').fadeOut(1000);", 2000 );		
	}else{
	jQuery('#passwordnotmatched').hide();
	}
 }

 function hide_by_id(idvalue){ 	
		jQuery('#'+idvalue).hide();
 }
 
</script>

<script language="javascript">
function validate()
{
		jQuery('#errorcon').html('');
		jQuery('#errorcon').hide();
		var pass1=jQuery('#newpassword').val();
		var pass2=jQuery('#conpassword').val();	
		var password=jQuery('#password').val();		
	
		//var pass_chk = /^[A-Za-z0-9"'\,\.\-\_\/\(\)\ ]{3,1000}$/;
		var pass_chk = /^(?=.*[0-9]+.*)(?=.*[a-zA-Z]+.*)[0-9a-zA-Z]{5,}$/; 
		
		if(password.trim()  =='' && pass2.trim()  =='' && pass1.trim()  =='')	
		{
			jQuery('#span_password1').show();
			jQuery('#span_password2').show();
			jQuery('#span_password3').show();	
			
			jQuery('#span_newpassword').html('Please enter password.');
			jQuery('#span_conpassword').html('Please enter password.');
			jQuery('#span_password').html('Please enter password.');			
			return false;
		}else if(password.trim()  =='' && pass1.trim()  =='')	
		{			
			jQuery('#span_password1').show();
			jQuery('#span_password2').show();
			jQuery('#span_newpassword').html('Please enter password.');
			jQuery('#span_password').html('Please enter password.');	
			jQuery('#span_password3').hide();
			jQuery('#span_conpassword').html('');
			return false;
		}else if(pass2.trim()  =='' && pass1.trim()  =='')	
		{	
			jQuery('#span_password2').show();
			jQuery('#span_password3').show();		
			jQuery('#span_conpassword').html('Please enter password.');
			jQuery('#span_newpassword').html('Please enter password.');
			jQuery('#span_password1').hide();			
			jQuery('#span_password').html('');
			
			return false;
		}else if(password.trim()  =='' && pass2.trim()  =='')	
		{			
			
			jQuery('#span_password3').show();
			jQuery('#span_password1').show();		
			jQuery('#span_conpassword').html('Please enter password.');
			jQuery('#span_password').html('Please enter password.');	
			jQuery('#span_password2').hide();		
			jQuery('#span_newpassword').html('');
			return false;
		}else if(password.trim()  =='')	
		{	
			jQuery('#span_password1').show();	
			jQuery('#span_password').html('Please enter password.');
			jQuery('#span_newpassword2').hide();	
			jQuery('#span_password2').hide();			
			jQuery('#span_password3').html('');
			jQuery('#span_newpassword').html('');			
					
			return false;
		}else if(pass1.trim()  =='')	
		{	
			jQuery('#span_password2').show();			
			jQuery('#span_newpassword').html('Please enter password.');		
			jQuery('#span_password3').hide();
			jQuery('#span_password1').hide();					
			jQuery('#span_password').html('');
			jQuery('#span_conpassword').html('');			
			return false;
		}else if(pass2.trim()  =='')	
		{			
			jQuery('#span_password3').show();	
			jQuery('#span_conpassword').html('Please enter password.');	
			jQuery('#span_password1').hide();		
			jQuery('#span_password2').hide();				
			jQuery('#span_newpassword').html('');			
			jQuery('#span_password').html('');
			return false;
		}
		if(!pass_chk.test(pass1.trim()))	
		{		
			jQuery('#span_password2').show();	
			jQuery('#span_password1').hide();	
			jQuery('#span_password3').hide();	
			jQuery('#span_newpassword').html('The password must be at least six characters and contain one or more numeric values.');
			jQuery('#newpassword').focus();
			return false;
		}
		if(pass1!=pass2)	
		{		
			jQuery('#span_password3').show();	
			jQuery('#span_password1').hide();	
			jQuery('#span_password2').hide();	
			jQuery('#span_conpassword').html('Re-type password and password must be same.');
			//jQuery('#conpassword').val('');
			jQuery('#conpassword').focus();
			return false;
		}
				
	}
	
	 
   $(document).ready(function() {
       //  setTimeout("jQuery('#errorcon').html('');", 2000 );	
      });


</script>