<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>

<script type="text/javascript">

    jQuery(document).ready(function($){

                $('select,input[title]').qtip({
                   position: {
                       my: 'left center',
                       at: 'right center'
                    },
                    style: {
                       classes: ''
                    }
                });
});

</script>

<style type="text/css">
</style>

<form id="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>customers/editpaymentdetails/id/<?php echo $this->id?>">
 	<div class="row-1 wrapper">
            <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-1" style="width:307px;" <? }else{?> class="maxheight col-1" style="width:220px;"<? }?> >
                    <div class="maxheight box">
                        <div class="padding"> 
                           <?php echo $this->render('logged_in_left_panel.phtml'); ?>
                        </div>
                    </div>
            </article> 
            
              <article class="maxheight col-2" <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?> style="width:548px;"<? }else{?> style="width:630px;" <? }?>>
                <div class="maxheight box">
                    <div class="padding"> 					           		
                       
                       <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Payment Details " style="width: 56px; height: 22px;margin-bottom: 25px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Payment Details </cufontext></cufon></h2>

                       <?php

                                    if(isset($this->paymentError))
                                    { ?>
                                            <span class="loginmessage" > <?php echo $this->paymentError;
                                            ?><br><br> </span>
                             <div class="clear"></div>
                                    <? }
                            ?>

                       <?php $obj=new Zend_Session_Namespace('Zend_Auth');
							if($obj->message): ?>
                       <span class="greencolor float_left">
                           <br />Your Credit Card information updated successfully.
                           <br><br></span>
                        <?php endif; ?>

                       
                        <div id="formcompanyDetails"  style="clear: both !important;">
						
							<div class="section">
								  <label><span>Credit Card Type<strong>*</strong></span>
                                                                      <select title="<?php echo SIGNUP_CREDIT_CARD_TYPE ?>"  name="card_type" id="card_type" class="validate[required]" onchange="change_cvv_num(this.value)">
                                    	<option value="Visa" <?php if($this->card_type=='Visa'){?> selected <?php }?>>Visa</option>
                                        <option value="Master Card" <?php if($this->card_type=='Master Card'){?> selected<?php }?>>Master Card</option>
                                        <option value="American Express" <?php if($this->card_type=='American Express'){?> selected<?php }?>>American Express</option>
                                    </select>
                                </label>
                                
                                <label id="maxlenght16cvv"><span>Card Number<strong>*</strong></span>
                                <input  autocomplete='off' title="<?php echo SIGNUP_CREDIT_CARD_NUMBER ?>" name="card_num_org" id="card_num_org"  maxlength="16"  value="<?php echo (isset($this->card_num))? htmlspecialchars(stripslashes($this->card_num)) : '';?>" onchange="validate_card_num()"/>
                                
                               
                                <div class="formError" onclick="hide_by_id('card_num_error_div')" id="card_num_error_div" style="top: 240px; left: 790px; margin-top: 0px; opacity: 0.87;display:none;"><div class="formErrorContent">* Please specify valid card number<br></div></div>
                                </label>                                                               
                                
                                <label><span>Expiration Date<strong>*</strong></span>
                               	<select title="<?php echo SIGNUP_CREDIT_CARD_EXPIRE ?>" name="expiry_month" id="expiry_month"  onchange="validate_month();" style="width:95px; float:left;">
                                    	<option value="0" selected>Month</option>
                                        <option value="01" <?php if($this->expiry_month=='01'){?> selected<?php }?>>January</option>
                                        <option value="02" <?php if($this->expiry_month=='02'){?> selected<?php }?>>February</option>
                                        <option value="03" <?php if($this->expiry_month=='03'){?> selected<?php }?>>March</option>
                                        <option value="04" <?php if($this->expiry_month=='04'){?> selected<?php }?>>April</option>
                                        <option value="05"<?php if($this->expiry_month=='05'){?> selected<?php }?>>May</option>
                                        <option value="06"<?php if($this->expiry_month=='06'){?> selected<?php }?>>June</option>
                                        <option value="07"<?php if($this->expiry_month=='07'){?> selected<?php }?>>July</option>
                                        <option value="08"<?php if($this->expiry_month=='08'){?> selected<?php }?>>August</option>
                                        <option value="09"<?php if($this->expiry_month=='09'){?> selected<?php }?>>September</option>
                                        <option value="10"<?php if($this->expiry_month=='10'){?> selected<?php }?>>October</option>
                                        <option value="11"<?php if($this->expiry_month=='11'){?> selected<?php }?>>November</option>
                                        <option value="12"<?php if($this->expiry_month=='12'){?> selected<?php }?>>December</option>
                                </select> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				
                                      <div onclick="hide_by_id('expiry_month_error_div')" id="expiry_month_error_div" class="expiry_monthformError formError" style="top: 290px; left: 790px; margin-top: 0px; opacity: 0.87;display:none;"><div
class="formErrorContent">*  Please specify expiry month/year.<br></div></div>
                            </label>
			    <label style='margin-left: 230px;margin-top:-60px'>
                                 <select  title="<?php echo SIGNUP_CREDIT_CARD_EXPIRE ?>" name="expiry_year" id="expiry_year" onchange="validate_year()" style="width:95px; margin-left:19px; float:left;"><option value="0" selected>Year</option>
                                      <option value="11"<?php if($this->expiry_year=='11'){?> selected<?php }?>>2011</option>
                                      <option value="12"<?php if($this->expiry_year=='12'){?> selected<?php }?>>2012</option>
                                      <option value="13"<?php if($this->expiry_year=='13'){?> selected<?php }?>>2013</option>
                                      <option value="14"<?php if($this->expiry_year=='14'){?> selected<?php }?>>2014</option>
                                      <option value="15"<?php if($this->expiry_year=='15'){?> selected<?php }?>>2015</option>
                                      <option value="16"<?php if($this->expiry_year=='16'){?> selected<?php }?>>2016</option>
                                      <option value="17"<?php if($this->expiry_year=='17'){?> selected<?php }?>>2017</option>
                                      <option value="18"<?php if($this->expiry_year=='18'){?> selected<?php }?>>2018</option>
                                      <option value="19"<?php if($this->expiry_year=='19'){?> selected<?php }?>>2019</option>
                                      <option value="20"<?php if($this->expiry_year=='20'){?> selected<?php }?>>2020</option>
                                      <option value="21"<?php if($this->expiry_year=='21'){?> selected<?php }?>>2021</option>
                                      <option value="22"<?php if($this->expiry_year=='22'){?> selected<?php }?>>2022</option>
                                      <option value="23"<?php if($this->expiry_year=='23'){?> selected<?php }?>>2023</option>
                                      <option value="24"<?php if($this->expiry_year=='24'){?> selected<?php }?>>2024</option>
                                      <option value="25"<?php if($this->expiry_year=='25'){?> selected<?php }?>>2025</option>
                                    </select>
				    </label>

                                <div onclick="hide_by_id('expiry_month_error_div')" id="expiry_month_error_div" class="expiry_monthformError formError" style="top: 385px; left: 878px; margin-top: 0px; opacity: 0.87;display:none;"><div
class="formErrorContent">*  Please specify expiry month/year.<br></div></div>
                                
                                <label><span>Name on Card<strong>*</strong></span><input title="<?php echo SIGNUP_CREDIT_CARD_NAME_ON_CARD ?>" name="card_name" id="card_name"  value="<?php echo (isset($this->card_name))? htmlspecialchars(stripslashes($this->card_name)) : '';?>"  onblur="validate_card_name()"/></label>
                                <div id="card_name_error_div" onclick="hide_by_id('card_name_error_div')" class="formError" style="top: 352px; left: 790px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify name on card.<br></div></div>
                                
                                 <label id="maxlenght3cvv"><span>CVV<strong>*</strong></span>										
                                <input  autocomplete='off' title="<?php echo SIGNUP_CVV ?>" name="card_cvv" id="card_cvv" maxlength="4" value="<?php echo (isset($this->card_cvv))? htmlspecialchars(stripslashes($this->card_cvv)) : '';?>" style="width:50px;" class="validate[required,custom[card_cvv]]" onblur="validate_card_cvv()"/>
                                <div id="card_cvv_error_div" onclick="hide_by_id('card_cvv_error_div')" class="formError" style="top: 405px; left: 650px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify valid CVV number<br></div></div>
                                </label>
                                
                                <div class="buttonsNextPrev">
                                   
                                  
                                  <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?> 
                               <input class="buttonsNext" type="button" value="Cancel"  onclick="window.location.href='<?php echo WEBSITE_URL?>customers/edit/id/<?php echo $this->id?>'" style="width:90px;"/>                                
                                  <? }else{?>  <input class="buttonsNext" type="button" value="Cancel"  onclick="window.location.href='<?php echo WEBSITE_URL?>customers/myaccount/id/<?php echo $this->id?>'" style="width:90px;"/>  <? }?>
                                  
                                <input class="buttonsNext" type="submit" value="Update"  onclick="return validate()" style="width:90px;"/> 
                               <input type="hidden"  name="id" id="id"   value="<?php echo (isset($this->id))? htmlspecialchars(stripslashes($this->id)) : '';?>"/>
                                <input name="card_num" id="card_num" type="hidden"  maxlength="16"  value="<?php echo (isset($this->card_num_org))? htmlspecialchars(stripslashes($this->card_num_org)) : '';?>"/>    
                               
                                	<?php if($this->card_type=='American Express'){?>
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="15"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="4"/>
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="amex"/>                                                                   	 	                                   										    
                                   	<? }else if($this->card_type=='Master Card'){?>
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="16"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="3"/>
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="mastercard"/>                                                                   	 	                                   										    
                                   	<? }else if($this->card_type=='Visa'){?>
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="16"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="3"/>    
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="visa"/>                                                                   	 	                                   										
                                   	<? }else{?>                                   	
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="16"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="3"/>                                                                   	 	                                   	
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="visa"/>                                                                   	 	                                   										
									<? }?>
                               
                               
                                                           
                                </div> 
							</div>
                        </div>
                    </div>
                </div>
            </article> 
			  </div>            
        </form>        
<script type="text/javascript">
  function change_cvv_num(cardtype){   
 	if(cardtype=='Visa'){ 	
 	 jQuery("#card_num_chk").val('16');
	 jQuery("#card_cvv_chk").val('3');
	 jQuery('#cardtype_vlaue').val('visa');	
 	}else if(cardtype=='Master Card'){ 
 	 jQuery("#card_num_chk").val('16');
	 jQuery("#card_cvv_chk").val('3');
	 jQuery('#cardtype_vlaue').val('mastercard');	
 	}else if(cardtype=='American Express'){ 
 	 jQuery("#card_num_chk").val('15');
	 jQuery("#card_cvv_chk").val('4');
	 jQuery('#cardtype_vlaue').val('amex');	
 	}
 }
 
 
 function hide_by_id(idvalue){ 	
		jQuery('#'+idvalue).hide();
 }
 
function validate_card_num()
{	
		var card_num_org=jQuery('#card_num_org').val();
		jQuery('#card_num').val(card_num_org);
		var card_num=jQuery('#card_num').val();
		var card_num_chk=jQuery('#card_num_chk').val();		
		var card_cvv_chk=jQuery('#card_cvv_chk').val();
		var cardtype=jQuery('#cardtype_vlaue').val();	
		if(card_num_chk==15 && card_cvv_chk==4 && cardtype=='amex'){	
		var cardchk = /^3[4,7]\d{13}$/;
		var cardcvvchk = /^[0-9]{4}$/;
		//alert('15== 4');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='visa'){	
		var cardchk = /^4\d{3}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='mastercard'){	
		var cardchk = /^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}	
		//alert('164');
		if(!cardchk.test(card_num)){			
			jQuery('#card_num_error_div').show();
			jQuery('#card_num').val('');
			jQuery('#card_num_org').val('');
		}else{
			
			jQuery('#card_num_error_div').hide();
		}	
}

function validate_month()
{
		var expiry_month=jQuery('#expiry_month').val();
		if(expiry_month == 0){
			jQuery('#expiry_month_error_div').show();
		}else{
			jQuery('#expiry_month_error_div').hide();
		}
}

function validate_year()
{
		var expiry_year=jQuery('#expiry_year').val();
		//var card_name=jQuery('#card_name').val();
		//var card_cvv=jQuery('#card_cvv').val();
		if(expiry_year == 0){
			jQuery('#expiry_month_error_div').show();
		}else{
			jQuery('#expiry_month_error_div').hide();
		}
}

function validate_card_name()
{
		var card_name=jQuery('#card_name').val();
		//var card_cvv=jQuery('#card_cvv').val();		
		if(card_name ==''){
			jQuery('#card_name_error_div').show();
		}else{
			jQuery('#card_name_error_div').hide();
		}	
}
 
function validate_card_cvv()
{

		var card_cvv=jQuery('#card_cvv').val();		
		var card_num_chk=jQuery('#card_num_chk').val();		
		var card_cvv_chk=jQuery('#card_cvv_chk').val();
		var cardtype=jQuery('#cardtype_vlaue').val();	
		
		if(card_num_chk==15 && card_cvv_chk==4 && cardtype=='amex'){	
		var cardchk = /^3[4,7]\d{13}$/;
		var cardcvvchk = /^[0-9]{4}$/;
		//alert('15== 4');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='visa'){	
		var cardchk = /^4\d{3}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='mastercard'){	
		var cardchk = /^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}
		
		if(!cardcvvchk.test(card_cvv)){			
			jQuery('#card_cvv_error_div').show();
		}else{
			jQuery('#card_cvv_error_div').hide();
		}	
}
 
function validate()
{
			
		var card_num=jQuery('#card_num').val();
		var expiry_month=jQuery('#expiry_month').val();	
		var expiry_year=jQuery('#expiry_year').val();
		var card_name=jQuery('#card_name').val();
		var card_cvv=jQuery('#card_cvv').val();		
		
		var card_num_chk=jQuery('#card_num_chk').val();		
		var card_cvv_chk=jQuery('#card_cvv_chk').val();	
		var cardtype=jQuery('#cardtype_vlaue').val();				
		
		if(card_num_chk==15 && card_cvv_chk==4 && cardtype=='amex'){
		var cardchk = /^3[4,7]\d{13}$/;
		var cardcvvchk = /^[0-9]{4}$/;
		//alert('15== 4');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='visa'){	
		var cardchk = /^4\d{3}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='mastercard'){	
		var cardchk = /^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}
								
		if(card_num=='' && expiry_month=='0' && expiry_year=='0' && card_name=='' && card_cvv=='')	
		{
			jQuery('#card_num_error_div').show();
			jQuery('#expiry_month_error_div').show();
			jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();	
			return false;
		}else if((expiry_month=='0') && (expiry_year=='0') && (card_name=='') && (card_cvv==''))	
		{			
			
			if(!cardchk.test(card_num)){
			jQuery('#card_num_error_div').show();
			}else{
			jQuery('#card_num_error_div').hide();
			}				
			jQuery('#expiry_month_error_div').show();
			jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();	
			return false;
		}else if((expiry_year=='0') && (card_name=='') && (card_cvv==''))	
		{	
			jQuery('#expiry_month_error_div').show();  // since month and year error both are same
			//jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();			
			return false;
		}else if((card_name=='') && (card_cvv==''))	
		{	
			jQuery('#expiry_month_error_div').hide();  // since month and year error both are same
			//jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();			
			return false;
		}else if(card_num=='')	
		{	
			
			if(!cardchk.test(card_num)){
			jQuery('#card_num_error_div').show();			
			}else{
			jQuery('#card_num_error_div').hide();
			}			
			/*jQuery('#card_num_error_div').hide();
			jQuery('#expiry_month_error_div').hide();
			jQuery('#expiry_year_error_div').hide();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();*/
			return false;
			
		}else if(expiry_month=='0')	
		{		
			//jQuery('#card_num_error_div').hide();
			jQuery('#expiry_month_error_div').show();
			/*jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();	*/
			return false;
		}else if(expiry_year=='0')	
		{	
			jQuery('#expiry_year_error_div').show();							
			return false;
		}else if(card_name=='')	
		{				
			jQuery('#card_name_error_div').show();
			return false;
		}else if(card_cvv=='')	
		{	
			jQuery('#card_num_error_div').hide();
			jQuery('#expiry_month_error_div').hide();
			jQuery('#expiry_year_error_div').hide();				
			jQuery('#card_name_error_div').hide();
			jQuery('#card_cvv_error_div').show();
			return false;
		}else{	
			
			if(!cardchk.test(card_num)){
			jQuery('#card_num_error_div').show();
			return false;
			}else{
			jQuery('#card_num_error_div').hide();
			}	
			if(!cardcvvchk.test(card_cvv)){
			jQuery('#card_cvv_error_div').show();
			return false;
			}else{
			jQuery('#card_cvv_error_div').hide();
			}				
			jQuery('#expiry_month_error_div').hide();
			jQuery('#expiry_year_error_div').hide();				
			jQuery('#card_name_error_div').hide();			
		}			
	}
 </script>  
 