<link href="<?php echo WEBSITE_CSS_URL . 'validationEngine.jquery.css' ?>" media="screen" rel="stylesheet" type="text/css" >
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL . 'jquery-1.4.2.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL . 'jquery.validationEngine-en.js' ?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL . 'jquery.validationEngine.js' ?>"></script>

<div id="title-box"><h1><cufon style="width: 102px; height: 40px;" alt="Forgot password" class="cufon cufon-canvas"><canvas style="width: 124px; height: 39px; top: 0px; left: -1px;" height="39" width="124"></canvas><cufontext>Forgot password</cufontext></cufon></h1></div>

<div id="content_box">

    <?php
    $obj = new Zend_Session_Namespace('Zend_Auth');

    if (isset($obj->loginError)) {
 ?>
        <span class="forgotmessage"> <?php echo $_SESSION['Zend_Auth']['loginError'];
        unset($_SESSION['Zend_Auth']['loginError']); ?><br/><br/> </span>
    <? }
    ?>

    <p align="center"><strong>Please enter your email address for resetting your password.</strong></p> <br /><br />

    <div id="signin-form">

        <form id="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL ?>customers/forgotpassword">

            <div class="input-item">
                <label for="log">Email Address</label>
                <input name="email" type="text" id="email"  class="validate[required,custom[email]] text" maxlength="200" style="width:215px;"/>
            </div>

            <div class="input-item">
                <input name="submit" value="Confirm" class="big-orange-bt" onclick="validate_signup()" type="submit">
            </div>            

        </form>


    </div>	</div>

<div id="bottom-box">
    <div class="clear"></div>
</div>
<div class="clear"></div>
<script type="text/javascript">
    function validate_signup(){
        // binds form submission and fields to the validation engine
        jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
    }
</script>