<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<?php echo$this->headScript()->prependFile(__JS_DIRECTORY__.'gen_validatorv2.js',$type='text/javascript'); ?>
<script src="<?php echo WEBSITE_EXTERNALJS_URL.'ui.datepicker.js'?>" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="<?php echo WEBSITE_CSS_URL.'ui.datepicker.css'?>" type="text/css" media="screen" charset="utf-8" />
<script type="text/javascript" charset="utf-8">
jQuery(function($){
$(".dateinput").datepicker();
});
</script>
<script type="text/javascript" charset="utf-8">
function getshow(id,position)
{
jQuery("#id").show();
}

function getpreview(id,position)
{
	var first_call_id=jQuery("#first_call_id").val();
	if(first_call_id!=id){
	jQuery("#first_call_id").val(id);
	//alert(id+"==>"+position);
	$(document).ready(function() {
	 var preview_hidden_value=jQuery('#preview_hidden_value').val();	
	if(id!=''){
//  var id=jQuery('#formid').val();

		jQuery.post("<?php echo WEBSITE_URL?>customers/popupinquirypreview",{inquiry_id:id,position:position},function(response){		//alert(response);
		//exit;
				if(response!=''){
					jQuery("#previewhiddendiv").fadeIn("slow");
					jQuery('#previewhiddendiv').html(response);	
				}else{
							
				}									
		});	
		jQuery('#preview_hidden_value').val('');
	}else{
	jQuery('#preview_hidden_value').val('');	
	}
});
}else{
jQuery("#previewhiddendiv").show();
}

}
function hideme(hidediv){              
           	  jQuery("#"+hidediv).hide();
 }

</script>
<div id="previewhiddendiv"></div>
<div class="row-1 wrapper">   
  <article class="maxheight" >
                <div class="maxheight box">
                    <div class="padding">

						<div class="topRow float_left">
						<input type="hidden" name="customers" id="customers_top_id" value="<?=$this->loggedinuser?>">
						<input type="hidden" name="first_call_id" id="first_call_id" value="0">						
						<span id="formsdiv">
                                                    <br /><br />
						<strong> Forms: </strong> <select class="select1" name="forms" id="forms_top_id"  onchange="serach(this.value,'form_id','<?=$this->page_number?>')" style="width:150px;">
						<option value="0">All forms</option>
						<?php foreach ($this->forms_data as $data_key =>$data_val) {?>
							<option value="<?php echo $data_val->id;?>" <?php if($this->drop_down_form_id==$data_val->id){ echo "selected";}?>><?php echo stripslashes(ucfirst($data_val->form_name)); ?></option>
						<? }?>
						</select></span>
						<strong> Billing Period:</strong>
						<span id="user_calender_first_time">						
						<input type="hidden" value="<?=$this->select_billing_ajax?>" name="select_billing_ajax_hidden_for_selected" id="select_billing_ajax_hidden_for_selected">
						 <select class="selectcustomer" style="margin-right:0;width:185px;" id="select_billing_ajax"  onchange="serach_date_by_user(this.value)">						 
						</select> 
						</span> 													 
						 <strong> Show:</strong> 
						<select class="selectcustomer" style="margin-right:0;width:130px;" onchange="serach_all_calls(this.value,'limit','<?=$this->page_number?>','<?php echo $this->drop_down_form_id?>')">						
						<!--<option value="0">Select Calls</option>-->
						<option value="1" <?php if($this->selectform==1){ echo "selected";}?>>All Inquiries</option>
						<option value="2" <?php if($this->selectform==2){ echo "selected";}?>>Incomplete</option>
						<option value="3" <?php if($this->selectform==3){ echo "selected";}?>>After hours</option>
						<option value="4" <?php if($this->selectform==4){ echo "selected";}?>>Hang up</option>
						<option value="5" <?php if($this->selectform==5){ echo "selected";}?>>Connected</option>		
						</select> 
						</div>							
                        <div class="clear"></div>

                        <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Reporting " style="width: 56px; height: 22px;margin-top: -165px;clear: both;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Reporting </cufontext></cufon></h2>
                        <div class="clear"></div>	
                          <?php
							$obj=new Zend_Session_Namespace('Zend_Auth');

							if(isset($obj->deleteError))
								{?>
                        <label style="height: 35px;"><span class="loginmessage" > <?php echo $_SESSION['Zend_Auth']['deleteError'];
									unset($_SESSION['Zend_Auth']['deleteError']);?><br><br> </span></label>
								<? }?>
						<?php 
						if(!empty($this->paginator) && count($this->paginator)>0)
							{?>
                                                    <div id="formcompanyDetails" style="width: 800px;">
							 <div class="table">
							 <div class="topRow1">	
							 
                                                             <span class="coloms call5view" style="width: 50px;">View</span>
							  <span class="coloms">	
								<? if($this->columnname!='date_created'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/date_created/sort/asc/page/<?php echo $this->page_number?>">
								Date
								</a><? }?>							
								
								<? if($this->columnname=='date_created' && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/date_created/sort/asc/page/<?php echo $this->page_number?>">Date
								<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle"></a>
								<? } ?>
								
								<? if($this->columnname=='date_created' && $this->sortby=='asc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/date_created/sort/desc/page/<?php echo $this->page_number?>">
								Date<img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;">
								</a><? }?>
								</span>	
								
                                                          <span class="coloms" style="width: 70px;">
								
								<? if($this->columnname!='time'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/time/sort/asc/page/<?php echo $this->page_number?>">
								Time
								</a><? }?>							
								
								<? if($this->columnname=='time' && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/time/sort/asc/page/<?php echo $this->page_number?>">Time
								<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle"></a>
								<? } ?>
								
								<? if($this->columnname=='time' && $this->sortby=='asc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/time/sort/desc/page/<?php echo $this->page_number?>">
								Time<img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;">
								</a><? }?>
								</span>			
							 
							 <?php 
							
								// USER DEFINED COLUMN		
								if(count($this->querylabel_array)>0 && $this->drop_down_form_id>0)
								{	
									for ($j=0;$j<count($this->querylabel_array);$j++) 
									{ 
											//echo $this->queryfield_array[$j]; echo "<br>";
									?>
								<span class="coloms">
								<? if($this->columnname!=$this->querylabel_array[$j]){?>
								<a style="text-decoration: none;"
								href="<?=WEBSITE_URL?>customers/reporting/customer_id/<?php echo $this->drop_down_customer_id?>/form_id/<?php echo $this->drop_down_form_id?>/name/<?=$this->queryfield_array[$j]?>/sort/asc/page/<?php echo $this->page_number?>">
								<?=$this->querylabel_array[$j]?>
								</a><? }?>							
								
								<? if($this->columnname==$this->queryfield_array[$j] && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/customer_id/<?php echo $this->drop_down_customer_id?>/form_id/<?php echo $this->drop_down_form_id?>/name/<?=$this->queryfield_array[$j]?>
								/sort/asc/page/<?php echo $this->page_number?>"><?=$this->querylabel_array[$j]?>
								<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle"></a>
								<? } ?>
								
								<? if($this->columnname==$this->queryfield_array[$j] && $this->sortby=='asc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/customer_id/<?php echo $this->drop_down_customer_id?>/form_id/<?php echo $this->drop_down_form_id?>/name/<?=$this->queryfield_array[$j]?>/sort/desc/page/<?php echo $this->page_number?>">
								<?=$this->querylabel_array[$j]?><img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;">
								</a><? }?>
								</span>
								<?} }else{ ?>	
													 						
							  	<span class="coloms">
								<? if($this->columnname=='firstname' && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/firstname/sort/asc/page/<?php echo $this->page_number?>">First Name
								<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle"></a>
								<? }else if($this->columnname=='firstname' && $this->sortby=='asc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/firstname/sort/desc/page/<?php echo $this->page_number?>">
								First Name<img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;">
								</a><? }else{?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/firstname/sort/asc/page/<?php echo $this->page_number?>">
								First Name
								</a>
								<? }?>
								</span>
								
								<span class="coloms">
								<? if($this->columnname=='lastname' && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/lastname/sort/asc/page/<?php echo $this->page_number?>">Last Name
								<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle"></a>
								<? }else if($this->columnname=='lastname' && $this->sortby=='asc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/lastname/sort/desc/page/<?php echo $this->page_number?>">Last Name
								<img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;">
								</a><? } else{?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/lastname/sort/asc/page/<?php echo $this->page_number?>">Last Name
								</a>
								<?} ?>
								</span>
								
								<span class="coloms" style="width: 120px;">
								<? if($this->columnname!='caller_id'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/caller_id/sort/asc/page/<?php echo $this->page_number?>">Phone
								</a>
								<? }?>
								<? if($this->columnname=='caller_id' && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/caller_id/sort/asc/page/<?php echo $this->page_number?>">Phone
								<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle">
								</a>
								<? }?>								
								<? if($this->columnname=='caller_id' && $this->sortby=='asc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/caller_id/sort/desc/page/<?php echo $this->page_number?>">Phone
								<img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;"></a><? }?>
								</span>
								<?php }?>
																									
                                                                <span class="coloms" style="width: 110px;">
								<? if($this->columnname!='call_duration'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/call_duration/sort/desc/page/<?php echo $this->page_number?>">Call Duration
								</a>
								<? }?>
								
								<? if($this->columnname=='call_duration' && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/call_duration/sort/asc/page/<?php echo $this->page_number?>">Call Duration
								<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle"></a><? }?>
								
								<? if($this->columnname=='call_duration' && $this->sortby=='asc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/call_duration/sort/desc/page/<?php echo $this->page_number?>">
								Call Duration<img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;">
								</a>
								<? }?>								
								</span>						
							
								
                                 <span class="coloms last" style="width: 100px;">
								<? if($this->columnname!='inquiry_type'){?><a  style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/name/inquiry_type/sort/desc/page/<?php echo $this->page_number?>">Inquiry Type</a><? }?>
								<? if($this->columnname=='inquiry_type' && $this->sortby=='desc'){?>
								<a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/inquiry_type/sort/asc/page/<?php echo $this->page_number?>">
								Inquiry Type<img src="<?=WEBSITE_URL?>images/down.png" style="vertical-align:middle">
								</a>
								<? }?>								
								<? if($this->columnname=='inquiry_type' && $this->sortby=='asc'){?><a style="text-decoration: none;" href="<?=WEBSITE_URL?>customers/reporting/form_id/<?php echo $this->drop_down_form_id?>/name/inquiry_type/sort/desc/page/<?php echo $this->page_number?>">Inquiry Type<img src="<?=WEBSITE_URL?>images/up.png" style="vertical-align:middle;"></a><? }?>
								</span>
							</div>
							
							<?php if(count($this->paginator)>0){?>
							<?php 
							$i=0; 
							$top_position=256;
							foreach ($this->paginator as $data_key =>$data_val) {
							?>
							<div  style="cursor:pointer;" <?php if( (($i)%2) == 0 ) { echo 'class="grayRow"';} else { echo 'class="whiteRow"'; } ?>>
                                                            <span onclick="getpreview('<?php echo $data_val->id;?>','<?=$top_position?>');" class="coloms call5view" style="width: 50px;"><img src="<?=WEBSITE_URL?>images/magnifingimages.jpeg" alt="view" title="view"></span>
        					<span class="coloms"><?php echo date('m/d/Y',strtotime($data_val->date_created)); ?></span>
                                                <span class="coloms" style="width: 70px;"><?php echo stripslashes($data_val->time); ?></span>
							<?php
							if(count($this->queryfield_array)>0 && $this->drop_down_form_id>0){
																
								for ($j=0;$j<count($this->queryfield_array);$j++) { $v = $this->queryfield_array[$j]; 
								if($v!=''){?>
								<span class="coloms"><?php if($data_val->{$v}==''){ echo "-----"; }else{ echo stripslashes(ucfirst($data_val->{$v})); } ?></span>
								<?	} } } else{?>		
								
							  <span class="coloms"><?php if($data_val->firstname==''){ echo "-----"; }else{ echo stripslashes(ucfirst($data_val->firstname)); } ?></span>
							  <span class="coloms"><?php if($data_val->lastname==''){ echo "-----"; }else{ echo stripslashes(ucfirst($data_val->lastname)); } ?></span>
							  <span class="coloms" style="width:120px;"><?php if($data_val->caller_id==''){ echo "-----"; }else{echo wordwrap($data_val->caller_id); } ?></span>
							<? } ?>						
						
							
                                                            <span class="coloms" style="width: 110px;"><?php if($data_val->call_duration==''){ echo "-----"; }else{

									//echo stripslashes(ucfirst($data_val->call_duration)); 
									if($data_val->call_duration>60)
									{
										$call_duration=$data_val->call_duration%60;
										if($call_duration<10)
										{
											$call_duration='0'.$call_duration;
										}
										
										$time=floor($data_val->call_duration/60);
										echo $time.":".$call_duration;
									}
									else{
										$call_duration=$data_val->call_duration;
										if($call_duration<10)
										{
											$call_duration='0'.$call_duration;
										}
										echo "0:".$call_duration;
									}
								
								} ?></span>								
								<span class="coloms last"  style="width: 100px;">
								<?php if(strtolower($data_val->inquiry_type)=='completed'){$data_val->inquiry_type='Connected';} echo stripslashes(ucfirst($data_val->inquiry_type)); ?>
								</span>
															
							</div>							
							<?php 					
								$i++;
								$top_position=$top_position+28;?>
								<?php
								}
							}?>							
						</div>											
						<div class="total"><?php echo $this->paginator; ?></div><br>
						<div class="total"> <span>Monthly Calls: <?php echo $this->total_inquires;?></span>  <span>Total Calls: <?php echo $this->total_calls;?></span>  <span>Total Inquires: <?php echo $this->total_calls;?></span> <span>Total Minutes: <?php echo $this->total_minutes;?></span></div>	
						</div>										
						<? } else{ ?>
						 <div id="formcompanyDetails">						
							 <div>								
							  <span>							   
							   <font color='black'><b>No Report found.</b></font>
							   </span>
							 </div>
						</div>	 
						<? }?>
                    </div>
                </div>
            </article>  
			  </div> 
<script type="text/javascript">
function serach(id,columnname,page_number){
	var cid=jQuery('#customers_top_id').val();		
	window.location.href='<?=WEBSITE_URL?>customers/reporting/customer_id/'+cid+'/form_id/'+id+'/page/'+page_number
}

function serach_date(page_number){
	
	var ftdate=jQuery('#select_billing_ajax').val();	
	var cid=jQuery('#customers_top_id').val();	
	var form_id=jQuery('#forms_top_id').val();
	
	/*alert(ftdate+'- in the 281 --');
	if(ftdate!='){
	 window.location.href='<?=WEBSITE_URL?>admin/inquiry/customer_id/'+cid+'/form_id/'+form_id+'/'+ftdate+'/page/'+page_number
	}else{		*/
		var fromdate=jQuery('#fromdate').val();		
		var todate=jQuery('#todate').val();		
		
		//alert(fromdate+'- in the 288 --'+todate);
		
		if(cid !='' && form_id!='' && todate!='' && fromdate!=''){			
		 window.location.href='<?=WEBSITE_URL?>customers/reporting/customer_id/'+cid+'/form_id/'+form_id+'/fromdate/'+fromdate+'/todate/'+todate+'/page/'+page_number
		}else if(todate!='' && fromdate!=''){				
		 window.location.href='<?=WEBSITE_URL?>customers/reporting/fromdate/'+fromdate+'/todate/'+todate+'/page/'+page_number
		}
	//}
}


function serach_date_by_user(serarch_fromdate_and_todate_included){		
	var cid=jQuery('#customers_top_id').val();	
	var form_id=jQuery('#forms_top_id').val();
	//var page_number=jQuery('#forms_top_id').val();
	var page_number=1;
	
	if(cid !='' && form_id!='' && serarch_fromdate_and_todate_included!=0){			
		 window.location.href='<?=WEBSITE_URL?>customers/reporting/customer_id/'+cid+'/form_id/'+form_id+'/'+serarch_fromdate_and_todate_included+'/page/'+page_number
	}	
}


function serach_all_calls(values,columnname,page_number,formid){	
window.location.href='<?=WEBSITE_URL?>customers/reporting/allforms/'+values+'/form_id/'+formid+'/page/'+page_number
}


function ajaxserach(customer_id){ 
		if(customer_id=='allcustomers'){
			alert(customer_id);
		jQuery('#formsdiv').hide();			
		window.location.href='<?=WEBSITE_URL?>customers/reporting/allcustomers/1';
		}else{			
		jQuery('#admin_calender_first_time').hide();
		jQuery('#user_calender_first_time').show();	
		jQuery('#formsdiv').show();
		jQuery('#ajaximageid').show();									
		jQuery.post("<?php echo WEBSITE_URL?>customers/getformsusingcustomerid",{customer_id: customer_id},function(response){		
			if(response!=''){
				jQuery('#ajaximageid').hide();
				jQuery('#forms_top_id').html(response);				
				}else{
				jQuery('#ajaximageid').hide();
				}				
		});	
		
		jQuery.post("<?php echo WEBSITE_URL?>customers/getbillingperiod",{customer_id: customer_id},function(response){		
			if(response!=''){
				//jQuery('#ajaximageid').hide();
				jQuery('#select_billing_ajax').show();	
				jQuery('#select_billing_ajax').html(response);				
				}else{
				//jQuery('#ajaximageid').hide();
				}				
		});	
	}
}


$(document).ready(function() {
	var cid=jQuery('#customers_top_id').val();	
	
	if(cid>0){
		//alert(cid);
		var selected_option=jQuery('#select_billing_ajax_hidden_for_selected').val();	
	jQuery.post("<?php echo WEBSITE_URL?>customers/getbillingperiodselected",{customer_id: cid,selected_option: selected_option},function(response){		
			jQuery('#admin_calender_first_time').hide();	
			if(response!=''){
				jQuery('#select_billing_ajax').show();
				jQuery('#select_billing_ajax').html(response);				
				}else{
				//jQuery('#ajaximageid').hide();
				}				
		});	
	}else{
		jQuery('#select_billing_ajax').hide();
		jQuery('#admin_calender_first_time').show();		
	}     // put all your jQuery goodness in here.
});




</script>	