<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>

<div id="title-box"><h1><cufon style="width: 102px; height: 40px;" alt="Reset Password" class="cufon cufon-canvas"><canvas style="width: 124px; height: 39px; top: 0px; left: -1px;" height="39" width="124"></canvas><cufontext>Reset Password</cufontext></cufon></h1></div>


<form id="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>customers/resetpassword">

    <div id="formPlanDetails" class="padding" style="width: 400px;margin: 0px auto;">
                          <fieldset>

                          <?php
							$obj=new Zend_Session_Namespace('Zend_Auth');

							if(isset($obj->loginError))
								{?>
									<span class="loginmessage" > <?php echo $_SESSION['Zend_Auth']['loginError'];
									unset($_SESSION['Zend_Auth']['loginError']);?><br><br> </span>
								<? }
				 		?>

			<label><p style="color:#303030;font-size:12px;margin:0 0 5px;padding:0;"  class="lableclasslogin">Password<strong  class="loginrequired">*</strong>
                                <span style="padding-left: 62px;">
                                <input style="width: 200px;" type="password"  name="pass" id="pass"  value="<?php //echo (isset($this->data->pass))? htmlspecialchars(stripslashes($this->data->pass)) : '';?>"  class="validate[required,custom[pass]] inputboxclasslogin"/>
                              	</span>
                                </p>
                         </label>
                         <label><p class="lableclasslogin">Re-type Password<strong  class="loginrequired">*</strong>
                                <span style="padding-left: 9px;">
                                    <input style="width: 200px;" type="password"  name="pass" id="pass"  value="<?php //echo (isset($this->data->pass))? htmlspecialchars(stripslashes($this->data->pass)) : '';?>"  class="validate[required,custom[pass]] inputboxclasslogin"/>
                              	</span>
                              	<br><div id="passwordnotmatched" class="formError"  style="top: 380px; left:659px;margin-top: 0px;opacity: 0.87;display:none;" onclick="hide_by_id('passwordnotmatched')"><div class="formErrorContent">* Please confirm your password</div></div>
                                </p>
                         </label>

                              <div style="float: right;height: 100px;margin-right: 53px;">

                       <input name="submit" type="submit" value="Confirm" style="width: 100px;" class="big-orange-bt float_left pad_0" onclick="validate_signup()">

                      <input name="reset_link" id="reset_link" value="Cancel" onclick="window.location.href='<?php echo WEBSITE_URL?>customers/login'" style="width: 100px;margin-left: 10px;" class="big-orange-bt float_left pad_0" type="button">

                      <input type="hidden"  name="reset_link" id="reset_link"  value="<?php echo $this->reset_link; ?>" />


                </div>

                            </fieldset>
                        </div>

        </form>

<div id="bottom-box">
    <div class="clear"></div>
</div>
<div class="clear"></div>
<script type="text/javascript">
 function validate_signup(){
              // binds form submission and fields to the validation engine
                jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
  }



 function validate_confirm_pass(){
	var pass1=jQuery('#pass').val();
	var pass2=jQuery('#re_pass').val();
	if(pass1!=pass2){
		jQuery('#passwordnotmatched').show();
		jQuery('#re_pass').val('');
		//jQuery('#re_pass').focus();
	}else{
	jQuery('#passwordnotmatched').hide();
	}
 }

 function hide_by_id(idvalue){
		jQuery('#'+idvalue).hide();
 }
</script>
