<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: signup.phtml	#
#			Description 	: this is First signup Page  to work in the front end site #
#			Created date	: 19/01/2011	#	
#			Created By		: Manoj Kumar Chauhan	#
######################################################
?> 
<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>

<script type="text/javascript">
 function validate_signup(){
 	
 				var emails=jQuery('#email').val(); 				
				jQuery('#email').val(jQuery.trim(emails));	
 	
              // binds form submission and fields to the validation engine
             // jQuery("#formID1").validationEngine('attach', {promptPosition : "topLeft"});
				jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
              // jQuery("#formID1").validationEngine('attach', {promptPosition : "bottomLeft"});
		      // jQuery("#formID1").validationEngine('attach', {promptPosition : "bottomRight"});
		     //  jQuery("#formID1").validationEngine('attach', {promptPosition : "topLeft"});
		     //document.formID1.submit();
 }
</script>

<script type="text/javascript">

    jQuery(document).ready(function($){

                $('label[title]').qtip({
                   position: {
                       my: 'left center',
                       at: 'right center'
                    },
                    style: {
                       classes: 'signupcss'
                    }
                });
});

</script>

<style type="text/css">
    #formUserDetails label span { width: 162px !important; color: #414145 !important;}
</style>

<div id="title-box"><h1><cufon style="width: 102px; height: 40px;" alt="Sign up" class="cufon cufon-canvas"><canvas style="width: 124px; height: 39px; top: 0px; left: -1px;" height="39" width="124"></canvas><cufontext>Sign up</cufontext></cufon></h1></div>

<form id="formID1" name="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>customers/signup">
 		<div class="row-1 wrapper" style="margin-top: -30px;">
            <article class="maxheight col-3">
                <div class="maxheight box"  style="width: 434px !important;margin-left: 20px;">
                    
                    <div class="padding">            		
                        <div id="formUserDetails">
                            <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="User Details " style="width: 56px; height: 22px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>User Details </cufontext></cufon></h2>

                            <br /><br />
                            
                            <fieldset>
                                <label title="<?php echo SIGNUP_FIRST_NAME; ?>"><span>First Name<strong>*</strong></span>
                            	 <input type="text" name="firstname" id="firstname" class="validate[required,custom[firstname]]" value="<?php echo (isset($this->data->firstname))? htmlspecialchars(stripslashes($this->data->firstname)) : '';?>" maxlength="50"/>
                                </label>

                                <label title="<?php echo SIGNUP_LAST_NAME; ?>"><span>Last Name<strong>*</strong></span><input type="text" name="lastname" id="lastname" class="validate[required,custom[lastname]]"  value="<?php echo (isset($this->data->lastname))? htmlspecialchars(stripslashes($this->data->lastname)) : '';?>"  maxlength="50"/>
                                
                                </label>
                                
                                <label><span>Company Name</span><input type="text" name="companyname" id="companyname"  value="<?php echo (isset($this->data->companyname))? htmlspecialchars(stripslashes($this->data->companyname)) : '';?>" maxlength="100"/></label>
                                
                                <label title="<?php echo SIGNUP_EMAIL; ?>"><span>Email Address<strong>*</strong></span><input type="text" name="email" id="email"  value="<?php echo (isset($this->data->email))? htmlspecialchars(stripslashes($this->data->email)) : '';?>"  class="validate[required,custom[email]]" onblur="validate_email()"  maxlength="50"/>
                                <div id="div_email" style="color:red;padding-left: 0px;font-weight:bold;width:250px;margin-left:150px;"></div>
                                </label>
                                                                
                                <label title="<?php echo SIGNUP_PASS1; ?>"><span>Password<strong>*</strong></span><input type="password"  name="pass" id="pass"  value="<?php //echo (isset($this->data->pass))? htmlspecialchars(stripslashes($this->data->pass)) : '';?>"  class="validate[required,custom[pass]]"  maxlength="20"/></label>
                                
                                <label title="<?php echo SIGNUP_PASS2; ?>"><span>Re-type Password<strong>*</strong></span><input type="password"   name="re_pass" id="re_pass"  value="<?php //echo (isset($this->data->pass))? htmlspecialchars(stripslashes($this->data->pass)) : '';?>"  class="validate[required,custom[re_pass]]" onblur="validate_confirm_pass()" maxlength="20"/><br>
                                <br>
                               
                                <div id="passwordnotmatched" class="formError"  style="top: 504px; left: 630px;  margin-top: 0px; opacity: 0.87;display:none;" onclick="hide_by_id('passwordnotmatched')"><div class="formErrorContent">* Please confirm your password</div> </div>
                                
                                </label>

                                <div class="input-item float_right">
                                        <input name="submit" value="Next" style="width: 212px;" class="big-orange-bt pad_0" onclick="validate_signup()" type="submit">


                               	<input type="hidden"  name="id" id="id"   value="<?php echo (isset($this->data->id))? htmlspecialchars(stripslashes($this->data->id)) : '';?>"/>
                       			<input type="hidden"  name="oldemail" id="oldemail"   value="<?php echo (isset($this->data->id))? htmlspecialchars(stripslashes($this->data->email)) : '';?>"/>
                               	<!--	<a class="buttonsNext" onclick="validate_signup()">Next</a>-->
                                </div>
                                
                            </fieldset>
                            </div>                       
                    </div>
                </div>
            </article>  
        </div>

 	</form>

<div id="bottom-box">
    <div class="clear"></div>
</div>
<div class="clear"></div>
<script type="text/javascript">
 //function validate_signup(){
              // binds form submission and fields to the validation engine
             // jQuery("#formID1").validationEngine('attach', {promptPosition : "topLeft"});
			//	jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
              // jQuery("#formID1").validationEngine('attach', {promptPosition : "bottomLeft"});
		      // jQuery("#formID1").validationEngine('attach', {promptPosition : "bottomRight"});
		     //  jQuery("#formID1").validationEngine('attach', {promptPosition : "topLeft"});
		     //document.formID1.submit();
 //}
 
 function validate_email(){ 
		var email=jQuery('#email').val();	
		var oldemail=jQuery('#oldemail').val();	
		
		var id=jQuery('#id').val();
		jQuery.post("<?php echo WEBSITE_URL?>customers/emailvalidation",{dos:'eck', email: email, id: id},function(response){		
			//alert(response);
				if(response>0){
				jQuery('#email').val('');
				jQuery('#email').val(oldemail);				
				//jQuery('#email').focus();						
				jQuery('#div_email').show();						
				jQuery('#div_email').html("&nbsp;" + email+' in use');
				setTimeout("jQuery('#div_email').fadeOut(1000);", 3000 );				
				}else{
				jQuery('#div_email').html('');				
				}				
		});	
}
	
 function validate_confirm_pass(){ 	
	var pass1=jQuery('#pass').val();
	var pass2=jQuery('#re_pass').val();
	if(pass1!=pass2){		
		jQuery('#passwordnotmatched').show();
		jQuery('#re_pass').val('');
		//jQuery('#re_pass').focus();
	}else{
	jQuery('#passwordnotmatched').hide();
	}
 }

 function hide_by_id(idvalue){ 	
		jQuery('#'+idvalue).hide();
 }
 
 
</script>