<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>

<style type="text/css">
    .formErrorContent{font-size: 11px !important; width: 177px !important}
    #formcompanyDetails label span { color: #414145 !important;}
</style>


<script type="text/javascript">

    jQuery(document).ready(function($){

                $('select,input[title]').qtip({
                   position: {
                       my: 'right center',
                       at: 'left center'
                    },
                    style: {
                       classes: ''
                    }
                });
});

</script>
<div id="title-box"><h1><cufon style="width: 102px; height: 40px;" alt="Sign up" class="cufon cufon-canvas"><canvas style="width: 124px; height: 39px; top: 0px; left: -1px;" height="39" width="124"></canvas><cufontext>Sign up</cufontext></cufon></h1></div>

<form id="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>customers/signupplanview/status/confirm/id/<?php echo $this->id;?>">
    <div class="row-1 wrapper" style="margin-top: -30px;">
            <article class="maxheight col-3">
                <div class="maxheight box"  style="width: 434px !important;float: left;">
                    <div class="padding">
                        <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Plan Details " style="width: 56px; height: 22px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Plan Details </cufontext></cufon></h2>
                        <div id="formPlanDetails">
                            <fieldset>                          
                             <?php 
                             foreach ($this->subscriptions as $subscription)
                             {
                             ?>
                                <p>  <input  onclick="showPaymentDiv(<?php echo $subscription['id'] ?>)" type="radio" name="plan_id" id="plan_id" value="<?php echo $subscription['id'];?>" <?php if($this->data->plan_id==$subscription['id']){ $plan_id = $subscription['id']; ?> checked <?php }?>  <?php if(5==$subscription['id']){ $plan_id = $subscription['id']; ?> checked <?php }?> class="validate[required]" accept="ftp://"/> <?php echo $subscription['name'];?> ($<?php echo $subscription['price'];?>)</p>
                            <?  } ?>                                
                            </fieldset>
                        </div>
                    </div>
                </div>
            </article>
            <article class="maxheight col-4">
                <div id="billing_div" class="maxheight box <?php if($plan_id == 5) echo 'hide'; else echo 'show' ?>" style="width: 403px !important;float: left;">
                    <div class="padding">
                        <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Payment Details " style="width: 56px; height: 22px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Payment Details </cufontext></cufon></h2>
                        <div id="formcompanyDetails"  style="margin-top: 25px;">
                            <fieldset>
                                <label><span>Credit Card Type<strong>*</strong></span>
                                	<select title="<?php echo SIGNUP_CREDIT_CARD_TYPE; ?>" name="card_type" id="card_type" class="validate[required]" onchange="change_cvv_num(this.value)">
                                    	<option value="Visa" <?php if($this->data->card_type=='Visa'){?> selected <?php }?>>Visa</option>
                                        <option value="Master Card" <?php if($this->data->card_type=='Master Card'){?> selected<?php }?>>Master Card</option>
                                        <option value="American Express" <?php if($this->data->card_type=='American Express'){?> selected<?php }?>>American Express</option>
                                    </select>
                                </label>
                                
                                <label><span>Card Number<strong>*</strong></span>
                                <input type="text"   autocomplete='off'  title="<?php echo SIGNUP_CREDIT_CARD_NUMBER; ?>" name="card_num" id="card_num"  class="validate[required,custom[card_num]]" maxlength="16"
                             	value="<?php echo (isset($this->card_num))? htmlspecialchars(stripslashes($this->card_num)) : '';?>"  onblur="validate_card_num()"   />
                                <div class="formError" onclick="hide_by_id('card_num_error_div')" id="card_num_error_div" style="top: 332px; left: 883px; margin-top: 0px; opacity: 0.87;display:none;"><div class="formErrorContent">* Please specify valid card number.<br></div></div>
                                </label>                                
                                
                                <label><span>Expiration Date<strong>*</strong></span>
                                    <select title="<?php echo SIGNUP_CREDIT_CARD_EXPIRE; ?>" name="expiry_month" id="expiry_month" style="width:95px; float:left;" onchange="validate_month()">
                                    	<option value="0" selected>Month</option>
                                        <option value="01" <?php if($this->data->expiry_month=='01'){?> selected<?php }?>>January</option>
                                        <option value="02" <?php if($this->data->expiry_month=='02'){?> selected<?php }?>>February</option>
                                        <option value="03" <?php if($this->data->expiry_month=='03'){?> selected<?php }?>>March</option>
                                        <option value="04" <?php if($this->data->expiry_month=='04'){?> selected<?php }?>>April</option>
                                        <option value="05"<?php if($this->data->expiry_month=='05'){?> selected<?php }?>>May</option>
                                        <option value="06"<?php if($this->data->expiry_month=='06'){?> selected<?php }?>>June</option>
                                        <option value="07"<?php if($this->data->expiry_month=='07'){?> selected<?php }?>>July</option>
                                        <option value="08"<?php if($this->data->expiry_month=='08'){?> selected<?php }?>>August</option>
                                        <option value="09"<?php if($this->data->expiry_month=='09'){?> selected<?php }?>>September</option>
                                        <option value="10"<?php if($this->data->expiry_month=='10'){?> selected<?php }?>>October</option>
                                        <option value="11"<?php if($this->data->expiry_month=='11'){?> selected<?php }?>>November</option>
                                        <option value="12"<?php if($this->data->expiry_month=='12'){?> selected<?php }?>>December</option>
                                </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </label>
                                <label style='margin-left: 230px;margin-top:-54px'>
                                <select title="<?php echo SIGNUP_CREDIT_CARD_EXPIRE; ?>" name="expiry_year" id="expiry_year" style="width:95px; margin-left:19px; float:left;" onchange="validate_year()">
                                      <option value="0" selected>Year</option>
                                      <option value="11"<?php if($this->data->expiry_year=='11'){?> selected<?php }?>>2011</option>
                                      <option value="12"<?php if($this->data->expiry_year=='12'){?> selected<?php }?>>2012</option>
                                      <option value="13"<?php if($this->data->expiry_year=='13'){?> selected<?php }?>>2013</option>
                                      <option value="14"<?php if($this->data->expiry_year=='14'){?> selected<?php }?>>2014</option>
                                      <option value="15"<?php if($this->data->expiry_year=='15'){?> selected<?php }?>>2015</option>
                                      <option value="16"<?php if($this->data->expiry_year=='16'){?> selected<?php }?>>2016</option>
                                      <option value="17"<?php if($this->data->expiry_year=='17'){?> selected<?php }?>>2017</option>
                                      <option value="18"<?php if($this->data->expiry_year=='18'){?> selected<?php }?>>2018</option>
                                      <option value="19"<?php if($this->data->expiry_year=='19'){?> selected<?php }?>>2019</option>
                                      <option value="20"<?php if($this->data->expiry_year=='20'){?> selected<?php }?>>2020</option>
                                      <option value="21"<?php if($this->data->expiry_year=='21'){?> selected<?php }?>>2021</option>
                                      <option value="22"<?php if($this->data->expiry_year=='22'){?> selected<?php }?>>2022</option>
                                      <option value="23"<?php if($this->data->expiry_year=='23'){?> selected<?php }?>>2023</option>
                                      <option value="24"<?php if($this->data->expiry_year=='24'){?> selected<?php }?>>2024</option>
                                      <option value="25"<?php if($this->data->expiry_year=='25'){?> selected<?php }?>>2025</option>
                                    </select> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </label>
                                    <div onclick="hide_by_id('expiry_month_error_div')" id="expiry_month_error_div" class="expiry_monthformError formError" style="top: 385px; left: 878px; margin-top: 0px; opacity: 0.87;display:none;"><div
class="formErrorContent">*  Please specify expiry month/year.<br></div></div>

				<!--<div id="expiry_year_error_div" onclick="hide_by_id('expiry_year_error_div')" class="expiry_yearformError formError" style="display:none;top: 350px; left: 870px; margin-top: 0px; opacity: 0.87;"><div class="formErrorContent">*  Please  specify expiry year.<br></div></div> -->
                               
                                <label><span>Name on Card<strong>*</strong></span>
                                <input type="text" title="<?php echo SIGNUP_CREDIT_CARD_NAME_ON_CARD; ?>" name="card_name" id="card_name"  value="<?php echo (isset($this->data->card_name))? htmlspecialchars(stripslashes($this->data->card_name)) : '';?>"  class="validate[required,custom[card_name]]"  onblur="validate_card_name()"/>
                                </label>
                                <div id="card_name_error_div" onclick="hide_by_id('card_name_error_div')" class="formError" style="top: 440px; left: 883px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify valid name on Card.<br></div></div>
                                
                                <label id="maxlenght3cvv"><span>CVV<strong>*</strong></span>
                                <input  autocomplete='off' title="<?php echo SIGNUP_CVV; ?>" name="card_cvv" id="card_cvv" maxlength="4" value="<?php echo (isset($this->data->card_cvv))? htmlspecialchars(stripslashes($this->data->card_cvv)) : '';?>" style="width:50px;" class="validate[required,custom[card_cvv]]" onblur="validate_card_cvv()"/>
                                </label>
                                <div id="card_cvv_error_div" onclick="hide_by_id('card_cvv_error_div')" class="formError" style="top: 495px; left: 860px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify valid CVV number.<br></div></div>
                                
                                <div class="maxheight box" style="width: 342px !important;">

                        <div id="formcompanyDetails">
                            <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Billing Address " style="width: 56px; height: 22px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Billing Address </cufontext></cufon></h2>

                            <br /><br />

                                <label><span>Address 1<strong>*</strong></span><input type="text" title="<?php echo SIGNUP_ADDRESS1; ?>" onblur="validate_address1()" name="address1"  id="address1" maxlength="250"   value="<?php echo (isset($this->data->address1))? htmlspecialchars(stripslashes($this->data->address1)) : '';?>" /></label>

                                <div id="address1_error_div" onclick="hide_by_id('address1_error_div')" class="formError" style="top: 604px; left: 860px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify Address1.<br></div></div>

                                <label><span>Address 2</span><input name="address2" type="text" id="address2" maxlength="250"  value="<?php echo (isset($this->data->address2))? htmlspecialchars(stripslashes($this->data->address2)) : '';?>"/></label>

                                <label><span>City<strong>*</strong></span><input type="text" title="<?php echo SIGNUP_CITY; ?>" name="city" id="city"  value="<?php echo (isset($this->data->city))? htmlspecialchars(stripslashes($this->data->city)) : '';?>"  maxlength="50" onblur="validate_city()" /></label>

                                <div id="city_error_div" onclick="hide_by_id('city_error_div')" class="formError" style="top: 712px; left: 860px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify city.<br></div></div>

                                <label><span>State<strong>*</strong></span><input type="text" title="<?php echo SIGNUP_STATE; ?>" name="state" id="state"  value="<?php echo (isset($this->data->state))? htmlspecialchars(stripslashes($this->data->state)) : '';?>"  maxlength="50" onblur="validate_state()" /></label>

                                <div id="state_error_div" onclick="hide_by_id('state_error_div')" class="formError" style="top: 767px; left: 860px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify state.<br></div></div>

                                <label><span>Zip<strong>*</strong></span><input type="text" title="<?php echo SIGNUP_ZIP; ?>" name="zip" id="zip"  value="<?php echo (isset($this->data->city))? htmlspecialchars(stripslashes($this->data->zip)) : '';?>"  maxlength="8" onblur="validate_zip()" /></label>

                                <div id="zip_error_div" onclick="hide_by_id('zip_error_div')" class="formError" style="top: 821px; left: 860px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify zip.<br></div></div>

                                <!-- <label>
                                    <span>State<strong>*</strong></span><input name="state" id="state"   value="<?php echo (isset($this->data->state))? htmlspecialchars(stripslashes($this->data->state)) : '';?>" style="width:50px; float:left;" maxlength="50"  class="validate[required,custom[state]]"/>
                                    <span style="width:40px; padding-left:18px;">Zip<strong>*</strong></span><input name="zip" maxlength="8"   value="<?php echo (isset($this->data->zip))? htmlspecialchars(stripslashes($this->data->zip)) : '';?>" style="width:80px;" id="zip"  class="validate[required,custom[zip]]"/>
                                </label> Old design-->
                                <label><span>Phone<strong>*</strong></span><input type="text" title="<?php echo SIGNUP_PHONE; ?>" name="phone" id="phone"   value="<?php echo (isset($this->data->phone))? htmlspecialchars(stripslashes($this->data->phone)) : '';?>" maxlength="15" onblur="validate_phone()" /></label>

                                <div id="phone_error_div" onclick="hide_by_id('phone_error_div')" class="formError" style="top: 874px; left: 860px; margin-top: 0px; opacity: 0.87; display:none;"><div class="formErrorContent">* Please specify phone number.<br></div></div>

                            </div>
                   
                </div>

                                <div class="float_right">

                                      <input name="submit" value="Back" style="width: 100px;" class="big-orange-bt float_left pad_0" onclick="window.location.href='<?php echo WEBSITE_URL?>customers/signup/id/<?php echo $this->id;?>'" type="button">

                                      <input name="submit" value="Next" style="width: 100px;margin-left: 10px;" class="big-orange-bt float_left pad_0" onclick="return validate()" type="submit">

                                   	<input type="hidden"  name="id" id="id"   value="<?php echo (isset($this->id))? htmlspecialchars(stripslashes($this->id)) : '';?>"/>                               
                                   	
                                   	<?php if($this->data->card_type=='American Express'){?>
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="15"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="4"/>
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="amex"/>                                                                   	 	                                   										    
                                   	<? }else if($this->data->card_type=='Master Card'){?>
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="16"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="3"/>
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="mastercard"/>                                                                   	 	                                   										    
                                   	<? }else if($this->data->card_type=='Visa'){?>
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="16"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="3"/>    
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="visa"/>                                                                   	 	                                   										
                                   	<? }else{?>                                   	
                                   	<input type="hidden"  name="card_num_chk" id="card_num_chk"   value="16"/>                                 
									<input type="hidden"  name="card_cvv_chk" id="card_cvv_chk"   value="3"/>                                                                   	 	                                   	
									<input type="hidden"  name="cardtype_vlaue" id="cardtype_vlaue"   value="visa"/>                                                                   	 	                                   										
									<? }?>
                                </div>                               
                            </fieldset>
                            
                        </div>
                    </div>
                    
                </div>

                <div id="free_div" class="<?php if($plan_id == 5) echo 'show'; else echo 'hide' ?>">
                    
                      <input name="submit" value="Back" style="width: 100px;" class="big-orange-bt float_left pad_0" onclick="window.location.href='<?php echo WEBSITE_URL?>customers/signup/id/<?php echo $this->id;?>'" type="button">

                      <input name="submit" value="Next" style="width: 100px;margin-left: 10px;" class="big-orange-bt float_left pad_0" type="submit">
                                      
                </div>
            </article>
        </div>
        </form>

<div id="bottom-box">
    <div class="clear"></div>
</div>
<div class="clear"></div>
<script type="text/javascript">

  function showPaymentDiv(plan_id)
  {      
      if(plan_id != 5)
      {
          //$("#formID1").validationEngine('init', {promptPosition : "centerRight", scroll: false})
          
          jQuery('#billing_div').removeClass('hide');
          jQuery('#billing_div').addClass('show');

          jQuery('#free_div').removeClass('show');
          jQuery('#free_div').addClass('hide');

      }
      else{
          jQuery('#billing_div').removeClass('show');
          jQuery('#billing_div').addClass('hide');

          jQuery('#free_div').removeClass('hide');
          jQuery('#free_div').addClass('show');

          //$('#formID1').validationEngine('hideAll');
      }
  }

  function change_cvv_num(cardtype){   
 	if(cardtype=='Visa'){ 	
 	 jQuery("#card_num_chk").val('16');
	 jQuery("#card_cvv_chk").val('3');
	 jQuery('#cardtype_vlaue').val('visa');	
 	}else if(cardtype=='Master Card'){ 
 	 jQuery("#card_num_chk").val('16');
	 jQuery("#card_cvv_chk").val('3');
	 jQuery('#cardtype_vlaue').val('mastercard');	
 	}else if(cardtype=='American Express'){ 
 	 jQuery("#card_num_chk").val('15');
	 jQuery("#card_cvv_chk").val('4');
	 jQuery('#cardtype_vlaue').val('amex');	
 	}
 }
 
 
 function hide_by_id(idvalue){ 	
		jQuery('#'+idvalue).hide();
 }
 
function validate_card_num()
{
		var card_num=jQuery('#card_num').val();
		var card_num_chk=jQuery('#card_num_chk').val();		
		var card_cvv_chk=jQuery('#card_cvv_chk').val();
		var cardtype=jQuery('#cardtype_vlaue').val();	
		if(card_num_chk==15 && card_cvv_chk==4 && cardtype=='amex'){	
		var cardchk = /^3[4,7]\d{13}$/;
		var cardcvvchk = /^[0-9]{4}$/;
		//alert('15== 4');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='visa'){	
		var cardchk = /^4\d{3}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='mastercard'){	
		var cardchk = /^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}	
		//alert('164');
		if(!cardchk.test(card_num)){			
			jQuery('#card_num_error_div').show();
		}else{
			
			jQuery('#card_num_error_div').hide();
		}	
}

function validate_month()
{
		var expiry_month=jQuery('#expiry_month').val();	
		if(expiry_month == 0){
			jQuery('#expiry_month_error_div').show();
		}else{
			jQuery('#expiry_month_error_div').hide();
		}	
}




function validate_year()
{
		var expiry_year=jQuery('#expiry_year').val();
		//var card_name=jQuery('#card_name').val();
		//var card_cvv=jQuery('#card_cvv').val();		
		if(expiry_year == 0){
			jQuery('#expiry_month_error_div').show();
		}else{
			jQuery('#expiry_month_error_div').hide();
		}	
}

function validate_card_name()
{
		var card_name=jQuery('#card_name').val();
		//var card_cvv=jQuery('#card_cvv').val();		
		if(card_name ==''){
			jQuery('#card_name_error_div').show();
		}else{
			jQuery('#card_name_error_div').hide();
		}	
}
 
function validate_card_cvv()
{

		var card_cvv=jQuery('#card_cvv').val();		
		var card_num_chk=jQuery('#card_num_chk').val();		
		var card_cvv_chk=jQuery('#card_cvv_chk').val();
		var cardtype=jQuery('#cardtype_vlaue').val();	
		
		if(card_num_chk==15 && card_cvv_chk==4 && cardtype=='amex'){	
		var cardchk = /^3[4,7]\d{13}$/;
		var cardcvvchk = /^[0-9]{4}$/;
		//alert('15== 4');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='visa'){	
		var cardchk = /^4\d{3}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='mastercard'){	
		var cardchk = /^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}
		
		if(!cardcvvchk.test(card_cvv)){		
			jQuery('#card_cvv_error_div').show();
		}else{
			jQuery('#card_cvv_error_div').hide();
		}	
}


function validate_address1()
{
    var address1=jQuery('#address1').val();
    if(address1 == ''){
            jQuery('#address1_error_div').show();
    }else{
            jQuery('#address1_error_div').hide();
    }
}

function validate_city()
{
    var city=jQuery('#city').val();
    if(city == ''){
            jQuery('#city_error_div').show();
    }else{
            jQuery('#city_error_div').hide();
    }
}

function validate_state()
{
    var state=jQuery('#state').val();
    if(state == ''){
            jQuery('#state_error_div').show();
    }else{
            jQuery('#state_error_div').hide();
    }
}

function validate_zip()
{
    var zip=jQuery('#zip').val();

    if(zip == '' || !zip.match(/^([0-9 ]{3,8})$/)){
            jQuery('#zip_error_div').show();
    }else{
            jQuery('#zip_error_div').hide();
    }
}

function validate_phone()
{
    var phone=jQuery('#phone').val();
    if(phone == '' || !phone.match(/^([\+][0-9]{1,3}[ \.\-])?([\(]{1}[0-9]{2,6}[\)])?([0-9 \.\-\/]{3,20})((x|ext|extension)[ ]?[0-9]{1,4})?$/)){
            jQuery('#phone_error_div').show();
    }else{
            jQuery('#phone_error_div').hide();
    }
}




 
function validate()
{                
		var card_num=jQuery('#card_num').val();
		var expiry_month=jQuery('#expiry_month').val();	
		var expiry_year=jQuery('#expiry_year').val();
		var card_name=jQuery('#card_name').val();
		var card_cvv=jQuery('#card_cvv').val();
                var address1=jQuery('#address1').val();
                var city=jQuery('#city').val();
                var state=jQuery('#state').val();
                var zip=jQuery('#zip').val();
                var phone=jQuery('#phone').val();
		
		var card_num_chk=jQuery('#card_num_chk').val();		
		var card_cvv_chk=jQuery('#card_cvv_chk').val();	
		var cardtype=jQuery('#cardtype_vlaue').val();				
		
		if(card_num_chk==15 && card_cvv_chk==4 && cardtype=='amex'){
		var cardchk = /^3[4,7]\d{13}$/;
		var cardcvvchk = /^[0-9]{4}$/;
		//alert('15== 4');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='visa'){	
		var cardchk = /^4\d{3}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}else if(card_num_chk==16 && card_cvv_chk==3 && cardtype=='mastercard'){	
		var cardchk = /^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$/;
 		var cardcvvchk = /^[0-9]{3}$/;
 		//alert('16== 3');
		}
								
		if(card_num=='' && expiry_month=='0' && expiry_year=='0' && card_name=='' && card_cvv=='')	
		{
			jQuery('#card_num_error_div').show();
			jQuery('#expiry_month_error_div').show();
			jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();	
			return false;
		}else if((expiry_month=='0') && (expiry_year=='0') && (card_name=='') && (card_cvv==''))	
		{			
			
			if(!cardchk.test(card_num)){
			jQuery('#card_num_error_div').show();
			}else{
			jQuery('#card_num_error_div').hide();
			}				
			jQuery('#expiry_month_error_div').show();
			jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();	
			return false;
		}else if((expiry_year=='0') && (card_name=='') && (card_cvv==''))	
		{	
			jQuery('#expiry_month_error_div').show();  // since month and year error both are same
			//jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();			
			return false;
		}else if((card_name=='') && (card_cvv==''))	
		{	
			jQuery('#expiry_month_error_div').hide();  // since month and year error both are same
			//jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();			
			return false;
		}else if(card_num=='')	
		{	
			
			if(!cardchk.test(card_num)){
			jQuery('#card_num_error_div').show();			
			}else{
			jQuery('#card_num_error_div').hide();
			}			
			/*jQuery('#card_num_error_div').hide();
			jQuery('#expiry_month_error_div').hide();
			jQuery('#expiry_year_error_div').hide();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();*/
			return false;
			
		}else if(expiry_month=='0')	
		{		
			//jQuery('#card_num_error_div').hide();
			jQuery('#expiry_month_error_div').show();
			/*jQuery('#expiry_year_error_div').show();				
			jQuery('#card_name_error_div').show();
			jQuery('#card_cvv_error_div').show();	*/
			return false;
		}else if(expiry_year=='0')	
		{	
			jQuery('#expiry_year_error_div').show();							
			return false;
		}else if(card_name=='')	
		{				
			jQuery('#card_name_error_div').show();
			return false;
		}else if(card_cvv=='')	
		{	
			jQuery('#card_num_error_div').hide();
			jQuery('#expiry_month_error_div').hide();
			jQuery('#expiry_year_error_div').hide();				
			jQuery('#card_name_error_div').hide();
			jQuery('#card_cvv_error_div').show();
			return false;
		}
                else if(address1 == '')
                {
                    jQuery('#address1_error_div').show();
                    return false;
                }
                else if(city == '')
                {
                    jQuery('#city_error_div').show();
                    return false;
                }
                else if(state == '')
                {
                    jQuery('#state_error_div').show();
                    return false;
                }
                else if(zip == '' || !zip.match(/^([0-9 ]{3,8})$/))
                {
                    jQuery('#zip_error_div').show();
                    return false;
                }
                else if(phone == '' || !phone.match(/^([\+][0-9]{1,3}[ \.\-])?([\(]{1}[0-9]{2,6}[\)])?([0-9 \.\-\/]{3,20})((x|ext|extension)[ ]?[0-9]{1,4})?$/))
                {
                    jQuery('#phone_error_div').show();
                    return false;
                }
                else{
			
			if(!cardchk.test(card_num)){
			jQuery('#card_num_error_div').show();
			return false;
			}else{
			jQuery('#card_num_error_div').hide();
			}	
			if(!cardcvvchk.test(card_cvv)){
			jQuery('#card_cvv_error_div').show();
			return false;
			}else{
			jQuery('#card_cvv_error_div').hide();
			}				
			jQuery('#expiry_month_error_div').hide();
			jQuery('#expiry_year_error_div').hide();				
			jQuery('#card_name_error_div').hide();			
		}			
	}

</script>