<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<form id="formID1" class="formular" method="post" action="#">
 	<div class="row-1 wrapper">
            <article class="maxheight col-3" style="width:926px;">
                <div class="maxheight box">
                    <div class="padding">            		
                                             
                        <div id="formPlanDetails">
                         <fieldset>    
                         <span style="color:black;font-size:14px;"><strong>We have received your information and have set up a new FormActivate
account for you. We have <br />sent an e-mail to the address on file, asking you
to activate your account. Once your account has been activated, you will be
able to use FormActivate right away.</strong></span>	
						 </fieldset>
                        </div>
                    </div>
                </div>
            </article>            
			  </div>            
</form>