        <div class="row-1 wrapper">
            <article class="maxheight col-1" style="width:220px;" >
                    <div class="maxheight box">
                        <div class="padding"> 
                            <?php   echo $this->render('admin_logged_in_left_panel.phtml'); ?>							
                        </div>
                    </div>
            </article>    
            <article class="maxheight col-2" style="width:706px;">
                <div class="maxheight box">
                    <div class="padding"> 					           		
                        <h3>Overview </h3>
                        <div id="formcompanyDetails">
							<div class="section">								
							</div>
                        </div>
                    </div>
                </div>
            </article>                  
        </div>
