<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: overview.phtml	#
#			Description 	: this is First step to create form builder
#			Created date	: 16/02/2011	#	
#			Created By		:						#
######################################################
?> 
<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>


<script type="text/javascript">


    jQuery(document).ready(function($){

                $('select, span[title]').qtip({
                   position: {
                       my: 'left center',
                       at: 'right center'
                    },
                    style: {
                       classes: ''
                    }
                });
});

</script>

<style type="text/css">
    #formUserDetails label span
    {
        font-weight: normal !important;
        padding: 0px;
    }
</style>
<div class="row-1 wrapper">
<article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-1" style="width:307px;" <? }else{?> class="maxheight col-1" style="width:220px;"<? }?> >
           <div class="maxheight box">
                        <div class="padding">    
                        
                        <?php /* if($this->admin_left_tab == 'admin_left_tab_for_customer'){ */ ?> 
                        <?php //echo $this->render('admin_logged_in_left_panel.phtml'); 
                       // } else {*/?>
                            <?php echo $this->render('admin_form_logged_in_left_panel.phtml'); //} ?>
                            
                        </div>
                    </div>
            </article>     
           
           <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-2" style="width:548px;" <? }else{?> class="maxheight col-4" style="width:706px;"<? }?> >
            <form id="formID1" name="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>adminforms/emailnotification/form_id/<?=$this->form_id?>/cid/<?=$this->cid?>">
                <div class="maxheight box">
                    <div class="forms-padding">            		

                        <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Email Notification " style="width: 56px; height: 22px;margin-bottom: 25px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Email Notification </cufontext></cufon></h2>
                        <div id="formUserDetails">
                            <fieldset>                                
                                <label style="color:#000000;">Send Notification Emails for the following Events:</label>
                                	
                                
                               <label  style="color:#000000;height:32px;"><span style="width:36px;padding: 2pt;">
                            	<input name="connections" id="connections" value="1" type="checkbox" <?php if($this->connections==1){?> checked <? }?> style="width:16px;"/>
                                      </span><span title="<?php echo CONNECTIONS; ?>">Connections Calls</span>
                                </label>

                                <label style="color:#000000;height:32px;"><span style="width:36px;padding: 2pt;">
                            	<input name="answered_calls" id="answered_calls" value="1" type="checkbox" <?php if($this->answered_calls==1){?> checked <? }?> style="width:16px;"/>
                            	</span>
                                    <span title="<?php echo ANSWER_CALL; ?>">Answered Calls</span>
                                </label>

                                <label style="color:#000000;height:32px;"><span style="width:36px;padding: 2pt;">
                            	<input name="unanswered_calls" id="unanswered_calls" value="1" type="checkbox" <?php if($this->unanswered_calls==1){?> checked <? }?> style="width:16px;"/>
                            	</span>
                                    <span title="<?php echo UNANSWER_CALL; ?>">Unanswered Calls</span>
                                </label>

                                <label style="color:#000000;height:32px;"><span style="width:36px;padding: 2pt;">
                            	<input name="after_hour_calls" id="after_hour_calls" value="1" type="checkbox" <?php if($this->after_hour_calls==1){?> checked <? }?> style="width:16px;"/>
                            	</span><span title="<?php echo AFTER_HOUR_CALL; ?>">After Hour Calls</span>
                                </label>

                                <label  style="color:#000000;height:32px;"><span  style="width:36px;padding: 2pt;"><input name="incomplete_calls" id="incomplete_calls" value="1" type="checkbox" <?php if($this->incomplete_calls==1){?> checked <? }?>  style="width:16px;"/>
                                    </span><span title="<?php echo INCOMPLETE_CALL; ?>">Incomplete Calls</span></label>
                                
                                <label style="color:#000000;height:39px;">Send Email Notification to prospective lead? 
                                <select name="send_email_notification_pros_leads" id="send_email_notification_pros_leads">
                                  <option value="no" <?php if($this->send_email_notification_pros_leads=='no'){?> selected<? }?>>No</option>
                                <option value="yes" <?php if($this->send_email_notification_pros_leads=='yes'){?>  selected<? }?>>Yes</option>
                             
                                </select>
                                </label>   
                                
                                <p style="color:#000000;"><strong style="color:red;">*</strong>Email Address for Notification: <br>
                               <textarea id="notification_email"  name="notification_email" cols="10" rows="5" style="width:200px; height:100px;" onblur="return validate_form()"><?php echo (isset($this->notification_email))? htmlspecialchars(stripslashes($this->notification_email)) : '';?></textarea><div class="emailformError formError" style="top: 507px; left: 755px;display:none; margin-top: 0px; opacity: 0.87;" id="email_notification_id_error"><div class="formErrorContent">* Please specify valid email address.<br></div></div>
                               <br>Enter one email address per line
                                </p>        
                                
								<div class="buttonsNextPrev" style="padding-right:20px;">  
								   <input type="hidden"  name="form_id" id="form_id"   value="<?php echo (isset($this->form_id))? htmlspecialchars(stripslashes($this->form_id)) : '';?>" />   
								   <input type="hidden"  name="email_notification_id" id="email_notification_id"   value="<?php echo (isset($this->email_notification_id))? htmlspecialchars(stripslashes($this->email_notification_id)) : '';?>" />   
								   <input class="buttonsNext" style="width:90px;" type="button" value="Previous" onclick="go_prev('Previous');"/>
								   <input class="buttonsNext" style="width:90px;" type="submit" value="Next" onclick="go_prev('Next')"/>
								   <input type="hidden" name="form_action" id="form_action" value="">
                                                                   <input type="hidden" name="jsflag" id="jsflag" value="">
 								</div> 
                            </fieldset>
                            </div>                       
                    </div>
                </div>
                </form>
            </article>
</div> 
<script type="text/javascript">
 function validate_form(){
 	var notification_email= jQuery.trim(jQuery('#notification_email').val());	
 	var notification_emails = notification_email.split(" ");
	var emails='';
	for(i = 0; i < notification_emails.length; i++){
		 	emails=emails+jQuery.trim(notification_emails[i]); 
	}
 		
 	var multiple_email_chk =/^(([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+([,.](([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+)*$/; 	 	
 	if(!multiple_email_chk.test(emails))	
			{
				//alert('Please enter valid email address.');
				jQuery('#notification_email').focus();
				jQuery('#email_notification_id_error').show();
				return false;
			}else{
			jQuery('#email_notification_id_error').hide();
			}
 }

 function go_prev(type)
 {

	jQuery('#form_action').val(type);
	var jsflag=jQuery('#jsflag').val();
	//return false;
 	validate_form();
 	//document.form.submit();
	if(jsflag==1){
 	document.formID1.submit();
	}
 	//var myString = '<?=WEBSITE_URL?>'+'forms/overview/form_id/'+'<?=$this->form_id;?>';	window.location=myString;
 }
 
// function go_prev(type)
// {
//	jQuery('#form_action').val(type);
//	validate_form();
// 	document.formID1.submit();
// }
 //
</script>

<?php

$session = new Zend_Session_Namespace('Zend_Auth');
$session->emailnotification_visited = true;

?>