<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: overview.phtml	#
#			Description 	: this is First step to create form builder
#			Created date	: 16/02/2011	#	
#			Created By		:						#
######################################################
?> 
<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.selectboxes.js' ?>"></script>

<script type="text/javascript">


    jQuery(document).ready(function($){

                $('select,input[title]').qtip({
                   position: {
                       my: 'left center',
                       at: 'right center'
                    },
                    style: {
                       classes: ''
                    }
                });
});

</script>

<style type="text/css">
    #formUserDetails label span {width: 166px !important;}
</style>

<div class="row-1 wrapper">
   <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-1" style="width:307px;" <? }else{?> class="maxheight col-1" style="width:220px;"<? }?> >
           <div class="maxheight box">
                        <div class="padding">
                            <?php echo $this->render('admin_form_logged_in_left_panel.phtml'); //} ?>
                        </div>
                    </div>
            </article>
           
           <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="col-2" style="width:548px;" <? }else{?> class="col-4" style="width:706px;"<? }?> >
               <form id="formID1" name="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>adminforms/overview/cid/<?=$this->cid?>">
                <div class="box" style="height:457px;margin-left: -37px;width: 709px;">
                    <div class="forms-padding">            		
                                        <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Form Overview " style="width: 56px; height: 22px;margin-bottom: 25px;clear: both;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Form Overview </cufontext></cufon></h2>

                        <div id="formUserDetails">
                            <fieldset>
                                <label><span>Form Name<strong>*</strong></span>
                            	 <input title="<?php echo OVERVIEW_FORM_NAME; ?>" name="formname" id="formname" class="validate[required,custom[formname]]" value="<?php echo (isset($this->formname))? htmlspecialchars(stripslashes($this->formname)) : '';?>" maxlength="50"/>
                                </label>
                                
                                <label><span>Status</span>
                                <select name="status" id="status" class="validate[required]" style="width:211px;">
                                <option value="1" <?php if($this->status=='1') echo "selected='selected'"; else '';?>>Active</option> 
                                <option value="0" <?php if($this->status=='0') echo "selected='selected'"; else '';?>>Inactive</option> 
                                </select>
                                </label>
                                
                                <label><span>Business Hours Connection Number<strong>*</strong></span><input title="<?php echo OVERVIEW_FORM_BUSNESPH; ?>" onchange="showDefault('business_phone_status', 1);hideme2('div_prorate', $('#business_phone').val(), 'business_phone_status');" name="business_phone" id="business_phone"  value="<?php echo (isset($this->business_phone))? htmlspecialchars(stripslashes($this->business_phone)) : '';?>"  class="validate[required,custom[phone]]" maxlength="20" />
                                    <span id="business_phone_status_ok" class="<?php echo (@$this->business_phone_validated == 1) ? 'show' : 'hide'; ?>">
                                        <img src="<?php echo WEBSITE_URL.'images/OK.png' ?>"/>
                                    </span>

                                    <span id="business_phone_status_error" class="hide">
                                        <input class="buttonsNext" type="button" value="Validate Number"  onclick="validatePhoneNumber($('#business_phone').val(), 'business_phone_status');"/>
<!--                                        Error, Try again-->
                                    </span>

                                    <span id="business_phone_status_default" class="<?php echo (@$this->business_phone_validated == 1) ? 'hide' : 'show'; ?>">
                                        <input class="buttonsNext" type="button" value="Validate Number"  onclick="validatePhoneNumber($('#business_phone').val(), 'business_phone_status');"/>
                                    </span>
                                </label>


                                <label><span>After Hours Connection Number</span><input title="<?php echo OVERVIEW_FORM_HOMEPH; ?>" onchange="showDefault('home_phone_status', 2);hideme2('div_prorate', $('#home_phone').val(), 'home_phone_status');"  name="home_phone" id="home_phone"  value="<?php echo (isset($this->home_phone))? htmlspecialchars(stripslashes($this->home_phone)) : '';?>"  maxlength="20" />
                                    <span id="home_phone_status_ok" class="<?php echo (@$this->home_phone_validated == 1) ? 'show' : 'hide'; ?>">
                                        <img src="<?php echo WEBSITE_URL.'images/OK.png' ?>"/>
                                    </span>

                                    <span id="home_phone_status_error" class="hide">
                                        <input class="buttonsNext" type="button" value="Validate Number"  onclick="validatePhoneNumber($('#home_phone').val(), 'home_phone_status');"/>
<!--                                        Error, Try again-->
                                    </span>

                                    <span id="home_phone_status_default" class="<?php echo (@$this->home_phone_validated == 1) ? 'hide' : 'show'; ?>">
                                        <input class="buttonsNext" type="button" value="Validate Number"  onclick="validatePhoneNumber($('#home_phone').val(), 'home_phone_status');"/>
                                    </span>

                                </label>
                                
                                
                                <label><span>Caller Id<strong>*</strong></span>

                                    <?php $caller_id = ($this->business_phone_validated || $this->home_phone_validated) ? $this->caller_id : '';  ?>

                                     <?php if($caller_id == ''): ?>
                                        <input type="hidden" name="business_phone_status" id="business_phone_status" value="0"/>
                                        <input type="hidden" name="home_phone_status" id="home_phone_status" value="0"/>
                                    <?php else:
                                        if($this->business_phone_validated == '1'): ?>
                                        <input type="hidden" name="business_phone_status" id="business_phone_status" value="1"/>
                                        <?php endif; if($this->home_phone_validated == '1'): ?>
                                        <input type="hidden" name="home_phone_status" id="home_phone_status" value="1"/>
                                    <?php endif; endif; ?>

                                    <select title="<?php echo OVERVIEW_FORM_CALLER_ID; ?>" class="validate[required,custom[caller_id]]" name="caller_id" id="caller_id" style="width: 250px;">

                                        <?php if($caller_id == ''): ?>

                                        <option value="">Please validate one or more numbers</option>
                                        <?php else: ?>
                                            <?php if(@$this->business_phone_validated == '1'): if($caller_id == @$this->business_phone) $sl1 = 'selected'; ?>
                                                <option <?php echo $sl1; ?> value="<?php echo @$this->business_phone; ?>">
                                                    Business Hours Connection Number
                                                </option>
                                            <?php endif; ?>

                                            <?php if(@$this->home_phone_validated  == '1'):  if($caller_id == @$this->home_phone) $sl2 = 'selected'; ?>
                                                <option <?php echo $sl2; ?> value="<?php echo @$this->home_phone; ?>">
                                                    After Hours Connection Number
                                                </option>
                                            <?php endif; ?>

                                        <?php endif; ?>

                                    </select>

                                </label>

                                <div class="buttonsNextPrev" style="margin-right: 246px;">
                            	<input class="buttonsNext"  style="width:90px;" type="button" value="Cancel"  onclick="window.location.href='<?php echo WEBSITE_URL?>adminforms/'"/> 
			                    <input class="buttonsNext"  style="width:90px;" type="submit" value="Next"  onclick="validate_form()"/> 
                               	<input type="hidden"  name="form_id" id="form_id"   value="<?php echo (isset($this->form_id))? htmlspecialchars(stripslashes($this->form_id)) : '';?>" />                                
                               	</div> 
                            </fieldset>
                            </div>                       
                    </div>
                </div>
                </form>

               <div id="div_prorate"></div>
            </article>
</div> 
<script type="text/javascript">
 function validate_form(){
              
              // binds form submission and fields to the validation engine
             // jQuery("#formID1").validationEngine('attach', {promptPosition : "topLeft"});
				jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
              // jQuery("#formID1").validationEngine('attach', {promptPosition : "bottomLeft"});
		      // jQuery("#formID1").validationEngine('attach', {promptPosition : "bottomRight"});
		     //  jQuery("#formID1").validationEngine('attach', {promptPosition : "topLeft"});
		     //document.formID1.submit();
 }

</script>

<script type="text/javascript">
 function validatePhoneNumber(number, number_type){

		if(number.trim() != ''){
                if(number_type == 'business_phone_status') $("#business_phone_status_default").html("<br />validating...");
                if(number_type == 'home_phone_status') $("#home_phone_status_default").html("<br />validating...");
		jQuery.post("<?php echo WEBSITE_URL?>forms/validate-phone-number",{number: number, number_type: number_type},function(response){
				if(response!=''){
				jQuery('#div_prorate').show();
				 jQuery('#div_prorate').html('');
				jQuery('#div_prorate').html(response);
				}else{
				jQuery('#div_prorate').hide();
				}
		});	}else{
			jQuery('#formUserDetailsdiverror').show();
		}
 }

 var hasOnePhoneNumber1 = $("#business_phone_status").val() == 1 ? true : false;
 var hasOnePhoneNumber2 = $("#home_phone_status").val() == 1 ? true : false;

 function showDefault(number_type, hideopt)
 {
    $("#"+number_type+"_ok").removeClass('show');
    $("#"+number_type+"_ok").addClass('hide');

    $("#"+number_type+"_error").removeClass('show');
    $("#"+number_type+"_error").addClass('hide');

    $("#"+number_type+"_default").removeClass('hide');
    $("#"+number_type+"_default").addClass('show');

    $("#"+number_type+"_default").html($("#"+number_type+"_error").html());

    if($('#caller_id option').size() == 1) {
        if(hideopt == 1 && hasOnePhoneNumber2 == false){
            $("#caller_id").removeOption(0);
            hasOnePhoneNumber1 = false;
            $("#business_phone_status").val(0);
        }
        else if (hideopt == 2 && hasOnePhoneNumber1 == false){
            $("#caller_id").removeOption(0);
            hasOnePhoneNumber2 = false;
            $("#home_phone_status").val(0);
        }
    }

    if($('#caller_id option').size() == 2)
    {
        if(hideopt == 1){
            $("#caller_id").removeOption(0);
            hasOnePhoneNumber1 = false;
            $("#business_phone_status").val(0);
        }
        else if (hideopt == 2){
            $("#caller_id").removeOption(1);
            hasOnePhoneNumber2 = false;
            $("#home_phone_status").val(0);
        }
    }

    if($('#caller_id option').size() == 0)
    {
        $("#caller_id").append("<option selected value=''>Please validate one or more numbers</option>");
        hasOnePhoneNumber1 = false; hasOnePhoneNumber2 = false;
        $("#business_phone_status").val(0);
        $("#home_phone_status").val(0);
    }
 }

 function hideme2(div_prorate, number, number_type){
    jQuery('#'+div_prorate).hide();
    if(number.trim() == '' || number_type == '') return false;
    if(number_type == 'business_phone_status') $("#business_phone_status_default").html("<br />validating...");
    if(number_type == 'home_phone_status') $("#home_phone_status_default").html("<br />validating...");

            var url  = "<?php echo WEBSITE_URL?>forms/get-phone-validate-status";
            $.ajax({
                type: "post",
                url : url,
                data: {number:number, number_type:number_type},
                success: function(response){

                    if(response == 1){
                        $("#"+number_type+"_error").removeClass('show');
                        $("#"+number_type+"_error").addClass('hide');

                        $("#"+number_type+"_default").removeClass('show');
                        $("#"+number_type+"_default").addClass('hide');

                        $("#"+number_type+"_ok").removeClass('hide');
                        $("#"+number_type+"_ok").addClass('show');

                        if(number_type == 'business_phone_status'){
                            var bn = jQuery.trim($("#business_phone").val());
                            var btext = $("#caller_id option[value='"+bn+"']").text();
                            if(btext.indexOf('Business Hours Connection Number') == -1){
                                if(hasOnePhoneNumber1 == false && hasOnePhoneNumber2 == false)
                                    $("#caller_id").removeOption(0);
                                $("#caller_id").append("<option value='"+bn+"'>Business Hours Connection Number</option>");
                                hasOnePhoneNumber1 = true;
                                $("#business_phone_status").val(1);
                            }

                        }
                        if(number_type == 'home_phone_status'){
                            var hn = jQuery.trim($("#home_phone").val());
                            var htext = $("#caller_id option[value='"+hn+"']").text();

                            if(htext.indexOf('After Hours Connection Number') == -1){
                                if(hasOnePhoneNumber1 == false && hasOnePhoneNumber2 == false)
                                    $("#caller_id").removeOption(0);
                                $("#caller_id").append("<option value='"+hn+"'>After Hours Connection Number</option>");
                                hasOnePhoneNumber2 = true;
                                $("#home_phone_status").val(1);
                            }
                        }
                    }
                    else{
                        $("#"+number_type+"_ok").removeClass('show');
                        $("#"+number_type+"_ok").addClass('hide');

                        $("#"+number_type+"_default").removeClass('show');
                        $("#"+number_type+"_default").addClass('hide');

                        $("#"+number_type+"_error").removeClass('hide');
                        $("#"+number_type+"_error").addClass('show');
                    }
                }
            });
 }
 function getradiovalue(radvalue){
 jQuery('#current_radiovalue').val(radvalue);
 }

</script>

<?php

$session = new Zend_Session_Namespace('Zend_Auth');
$session->overview_visited = true;

?>