<?php
######################################################
#			Organisation    : Synapse communications pvt. ltd.
#			File 			: overview.phtml	#
#			Description 	: this is First step to create form builder
#			Created date	: 16/02/2011	#	
#			Created By		:						#
######################################################
?> 
<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL . 'js/jquery.qtip.js' ?>"></script>
<script type="text/javascript">


    jQuery(document).ready(function($){

                $('.buttonsNextPreviewSignin[title], .ptip[title]').qtip({
                   position: {
                       my: 'right center',
                       at: 'left center'
                    },
                    style: {
                       classes: ''
                    }
                });

                $('.shelp[title]').qtip({
                   position: {
                       my: 'left center',
                       at: 'right center'
                    },
                    style: {
                       classes: ''
                    }
                });
});

</script>
<div class="row-1 wrapper">
 		    <?php
            $n=1;  
            $selected_field_id=array();
 		    foreach ($this->selected_fields as $selected_fields)
 		    {
                $selected_field_id[$n]=$selected_fields['field_id'];
	        	$selected_labels[$n]=$selected_fields['label'];	        	
	        	$selected_field_required[$n]=$selected_fields['field_required'];
	        	$selected_field_validate[$n]=$selected_fields['field_validate'];
	        	$selected_field_announce[$n]=$selected_fields['field_announce'];	        	
	        	$n++;
           }
           ?>
<article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-1" style="width:307px;" <? }else{?> class="maxheight col-1" style="width:220px;"<? }?> >
           <div class="maxheight box">
                        <div class="padding">    
                        
                        <?php /* if($this->admin_left_tab == 'admin_left_tab_for_customer'){ */ ?> 
                        <?php //echo $this->render('admin_admin_form_logged_in_left_panel.phtml'); 
                       // } else {*/?>
                            <?php echo $this->render('admin_form_logged_in_left_panel.phtml'); //} ?>
                            
                        </div>
                    </div>
            </article>     
           
           <article <?php if($this->admin_left_tab == 'admin_left_tab_for_customer'){ ?>  class="maxheight col-2" style="width:598px;margin-left: -50px;" <? }else{?> class="maxheight col-4" style="width:706px;"<? }?> >
           <form id="formID1" name="formID1" class="formular" method="post" action="<?php echo WEBSITE_URL?>adminforms/stdfield/form_id/<?=$this->form_id?>/cid/<?=$this->cid?>">
                <div class="maxheight box">
                    <div class="forms-padding">
                    <span style="float:right;">
                             <?php $session = new Zend_Session_Namespace('Zend_Auth'); if ($session->overview_done && $session->standard_form_done && $session->emailnotification_done && $session->redirect_done): ?>
                             <a style="border: solid 1px #CECECE;color: #949494;padding: 5px;" href="<?php echo WEBSITE_URL?>adminforms/preview/form_id/<?php echo $this->form_id?>/cid/<?=$this->cid;?>" title="<?php echo STDFIELD_PREVIEW; ?>" type="button" class="buttonsNextPreviewSignin">Preview Form</a>
                             <?php else: ?>

                                <span class="ptip" title="<?php echo STDFIELD_PREVIEW; ?>" style="border: solid 1px #CECECE;color: #949494;padding: 5px;">
                                    Preview Form
                                </span>
                             <?php endif; ?>
                        </span>

                        <h2 class="entry-title"><cufon class="cufon cufon-canvas" alt="Standard Form Fields " style="width: 56px; height: 22px;margin-bottom: 25px;"><canvas width="74" height="22" style="width: 74px; height: 22px; top: 0px; left: -1px;"></canvas><cufontext>Standard Form Fields </cufontext></cufon></h2>

                        <div id="formUserDetailsStd">
                                            
                        <b title="<?php echo STDFIELD_HELP; ?>" class="shelp">What is standard form field ? (i)    </b><br /><br />
                        	<table cellpadding="0" cellspacing="0" width="100%">
                        	<tr>
		                  		<td><b>Include</b></td>
		                  		<td><b>Field Type</b></td>
		                  		<td><b>Label</b></td>		                  		
		                  		<td style="width:49px;"><b>Required</b></td>
		                  		<td style="width:63px;"><b>Validation</b></td>
		                  		<td style="width:49px;"><b>Announce</b></td>
		                  		
		                  	</tr>
                        <?php
                        $i=0;
                        $key='';
                        foreach ($this->fields as $fields)
                        {
                        	//echo $fields['label'].'<br/>';	
                        	
                        	if($i%2==0)
                        	{
                        		$style="style='background-color:#EFF0F0'";
                        	}
                        	else {
                        		$style="";
                        	}
                        ?>
                  	      	<tr>
		                  		<td <?=$style?>>
		                  		<?php
		                  		$key='';
		                  		$key=array_search($fields['field_id'],$selected_field_id);
		                  		if($key!='')
		                  		{
		                  			$checked=" checked='checked'";
		                  			
		                  		}
		                  		else {
		                  			
		                  			$checked='';
		                  		}
		                  		?>
		                  			<input <?php echo in_array($fields['field_id'], array(4)) ? "id='ucheck' onclick='preventUncheck()'" : '' ?> type="checkbox" name="field_id[]" value="<?php echo $fields['field_id']?>" <?=$checked?> <?php if(!$session->standard_form_done && in_array($fields['field_id'], array(1, 2, 3, 4)) ) echo 'checked'; ?>>
		                  		</td>
		                  		<td <?=$style?>><?php echo $fields['field_type']?>
		                  		<input type='hidden' name="field_type[]" value="<?php $fields['field_type']; ?>" />
		             <input type='hidden' name="validate_class[]" value="<?php echo $fields['validate_class']; ?>" />
		             <input type='hidden' name="inquiry_table_field[]" value="<?php echo $fields['inquiry_table_field']; ?>" />
		             
		                  		
		                  		
		                  		
		                  		</td>
		                  		<td <?=$style?>><input type="text" name="label[]" maxlength="30" style="width:90px;" value="<?php 
		                  		//echo $key."==>".$selected_labels[$key];
		                  	
		                  		if($key!='') {
		                  			echo $selected_labels[$key];
		                  		}
		                  		else {
		                  			echo $fields['label'];
		                  		}?>" /></td>
		                  		
		                  		<td <?=$style?>>
		                  		<?php
		                  		$field_required='';
		                  		if($key!='') {
		                  			$field_required=$selected_field_required[$key];
		                  		}
		                  		else {
		                  			$field_required='';
		                  		}
		                  		?>
		                  		<select name="field_required[]" style="width:49px;">
							                  		<option value="no" <?php if($field_required=='no') { echo "selected='selected'"; }?>>No</option>
							                  		<option value="yes"
                                                                                                 <?php if($field_required=='yes') { echo "selected='selected'"; }?>
                                                                                                 <?php if(!$session->standard_form_done && in_array($fields['field_id'], array(3, 4, 9))) echo 'selected'; else if($session->standard_form_done && in_array($fields['field_id'], array(3, 4, 9)) && !array_search($fields['field_id'],$selected_field_id) ) echo 'selected'; ?>

                                                                                                >Yes</option>
							                  	</select>
		                  		</td>
		                  		<td <?=$style?>>
		                  		     		<?php
		                  		$field_validate='';
		                  		if($key!='') {
		                  			$field_validate=$selected_field_validate[$key];
		                  		}
		                  		else {
		                  			$field_validate='';
		                  		}
		                  		?>
		                  		
		                  		<select name="field_validation[]"  style="width:63px;">
							                  		<option value="none"  <?php if($field_validate=='none') { echo "selected='selected'"; }?>>None</option>
							                  		<option value="email" <?php if($field_validate=='email') { echo "selected='selected'"; }?>>Email</option>
							                  		<option value="zip" <?php if($field_validate=='zip') { echo "selected='selected'"; }?>>Zip</option>
							                  		<option value="phone" <?php if($field_validate=='phone') { echo "selected='selected'"; }?>>Phone</option>
		                  						</select>
		                  		</td>
		                  		
		                  		
		                  		<td <?=$style?>>
		                  		<?php
		                  		$field_announce='';
		                  		if($key!='') {
		                  			$field_announce=$selected_field_announce[$key];
		                  		}
		                  		else {
		                  			$field_required='';
		                  		}
                                                $session = new Zend_Session_Namespace('Zend_Auth');
		                  		?>
		                  		<select name="field_announce[]"  style="width:49px;">
                                                        <option value="no" <?php if($field_announce=='no') { echo "selected='selected'"; }?> >No</option>
                                                        <option value="yes" <?php if($field_announce=='yes') { echo "selected='selected'"; }?> <?php if(!$session->standard_form_done && in_array($fields['field_id'], array(1, 2)) ) echo 'selected'; else if($session->standard_form_done && in_array($fields['field_id'], array(1, 2)) && !array_search($fields['field_id'],$selected_field_id) ) echo 'selected'; ?> >Yes</option>
                                                </select>
		                  		
		                  		</td>
		                  		
		                  		
		                  		
		                  		
		                  	</tr>
                          	
                        <?php
						$i++; 
                         }
                        ?>
                        
                        </table>
                        </div>
                         <div class="buttonsNextPrev">                                
                           <input class="buttonsNext" style="width: 90px;" type="button" value="Previous" onclick="go_prev('Previous')"/>
                           <input class="buttonsNext" style="width: 90px;" type="submit" value="Next" onclick="go_prev('Next')"/>
                           <input type="hidden" name="preview_hidden_value" id="preview_hidden_value" value="<?php echo $this->preview_hidden_value;?>">                             
                             <input type="hidden" name="form_action" id="form_action" value="">    	
                             <input type="hidden" name="formid" id="formid" value="<?php echo $this->form_id;?>">    	
                         </div>      	
                     </div>
                </div>
                </form>
            </article>
</div> 
<div id="previewhiddendiv"></div>
<script type="text/javascript">
 function preventUncheck()
 {
     $("#ucheck").attr('checked', 'checked');
////     alert($("#ucheck").is(':checked'));
////     return ;
//     if($("#ucheck").is(':checked') == true)
//     {
//         $("#ucheck").attr('checked', 'checked');
//     }
//     else
//         alert('unchecked');
 }
 function validate_form(){
              // binds form submission and fields to the validation engine          
				jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
 }
 
 /*function go_prev()
 {
	var myString = '<?=WEBSITE_URL?>'+'adminforms/overview/form_id/'+'<?=$this->form_id;?>/cid/<?=$this->cid?>';	window.location=myString;
 }*/
 
 function go_prev(type)
 {
	jQuery('#form_action').val(type);	
 	validate_form();
 	//document.form.submit();
 	//var myString = '<?=WEBSITE_URL?>'+'adminforms/overview/form_id/'+'<?=$this->form_id;?>/cid/<?=$this->cid?>';	window.location=myString;
 	document.formID1.submit();
 	//var myString = '<?=WEBSITE_URL?>'+'forms/overview/form_id/'+'<?=$this->form_id;?>';	window.location=myString;
 }
 
 
 
</script>

<script type="text/javascript">
function validate_form(){
              // binds form submission and fields to the validation engine
           	  jQuery("#formID1").validationEngine('attach', {promptPosition : "centerRight"});
 }
  
function savepreviewform(){  	         
       jQuery('#preview_hidden_value').val('1');				       
       document.formID1.submit();
 } 
 
$(document).ready(function() {
	 var preview_hidden_value=jQuery('#preview_hidden_value').val();	
	if(preview_hidden_value==2){
  var id=jQuery('#formid').val();
		jQuery.post("<?php echo WEBSITE_URL?>adminforms/popupstdpreview/cid/<?=$this->cid?>",{form_id:id},function(response){		
				if(response!=''){
					jQuery("#previewhiddendiv").show();
					jQuery('#previewhiddendiv').html(response);	
				}else{
				jQuery('#previewhiddendiv').html('');				
				}									
		});	
		jQuery('#preview_hidden_value').val('');
	}else{
	jQuery('#preview_hidden_value').val('');	
	}
});


function hideme(hidediv){              
           	  jQuery("#"+hidediv).hide();
 }
</script>

<?php

$session = new Zend_Session_Namespace('Zend_Auth');
$session->standard_form_visited = true;

?>