<link href="<?php echo WEBSITE_CSS_URL.'validationEngine.jquery.css'?>" media="screen" rel="stylesheet" type="text/css" >	
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery-1.4.2.min.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine-en.js'?>"></script>
<script type="text/javascript" src="<?php echo WEBSITE_EXTERNALJS_URL.'jquery.validationEngine.js'?>"></script>
<form id="formID1" class="formular" method="post" action="#">
 	<div class="row-1 wrapper">
            <article class="maxheight col-3" style="width:926px;">
                <div class="maxheight box">
                    <div class="padding">            		
                                             
                        <div id="formPlanDetails">
                         <fieldset>    
                         <span style="color:black;font-size:14px;"><strong>
                          <?php
							$obj=new Zend_Session_Namespace('Zend_Auth');

							if(isset($obj->runtime_session))
								{?>
									<span class="loginmessage" > <?php echo $_SESSION['Zend_Auth']['runtime_session'];
									unset($_SESSION['Zend_Auth']['runtime_session']);?><br><br> </span>
								<? }
				 		?>
                         
                         </strong></span>	
						 </fieldset>
                        </div>
                    </div>
                </div>
            </article>            
			  </div>            
</form>